export interface SeedFood {
  name: string;
  slug: string;
  category: string;
  emoji: string;
  description: string;
  introAgeText: string;
  introAgeMonths: number;
  isAllergen: boolean;
  allergenName: string;
  containsAllergens: string;
  chokingRisk: string;
  nutrition: string;
  benefits: string;
  howToChoose: string;
  serve69: string;
  serve912: string;
  serve12Plus: string;
  storage: string;
  isIronRich: boolean;
  isProteinRich: boolean;
}

export const seedFoods: SeedFood[] = [
  // ---------------- FRUITS ----------------
  {
    name: "Banana", slug: "banana", category: "Fruits", emoji: "🍌",
    description: "A perfect first food: soft, sweet, portable, and easy for little hands to grip. Ripe bananas mash with gums alone.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Potassium, vitamin B6, fiber, vitamin C",
    benefits: "Provides quick energy plus potassium for fluid balance and B6 for brain development. Gentle on tummies and rarely allergenic.",
    howToChoose: "Pick bananas with brown speckles — they are sweeter and softer. Green bananas are starchy and harder to digest.",
    serve69: "Cut a whole banana in half, then peel the top half down to expose a 2-inch handle. Or offer a thick spear rolled in crushed baby cereal or hemp seeds for grip.",
    serve912: "Offer bite-sized pieces or thick spears. Let baby practice with a pre-loaded fork. Great mashed on toast fingers.",
    serve12Plus: "Whole banana with partial peel so your toddler can practice peeling. Slice into coins for snacks or freeze for nice-cream.",
    storage: "Counter 2–5 days. Peel and freeze ripe chunks in a bag for smoothies. Refrigerating slows ripening but darkens peel.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Avocado", slug: "avocado", category: "Fruits", emoji: "🥑",
    description: "Creamy, nutrient-dense, and rich in the healthy fats babies need for brain growth. Soft ripe flesh needs no cooking.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Healthy fats, folate, fiber, potassium, vitamin E",
    benefits: "One of the best brain foods for babies — fats support myelin development. Folate supports cell growth. Very satiating.",
    howToChoose: "Gently squeeze: ripe avocados yield slightly. Avoid rock-hard (unripe) or mushy (overripe) ones.",
    serve69: "Slice ripe avocado into thick spears (adult-finger sized). Roll in hemp seeds or crushed cheerios — avocado is slippery! Or mash and spread thickly on toast.",
    serve912: "Offer small cubes with skin partly on for grip, or spears. Mash onto toast, mix into oatmeal, or add to pasta sauce.",
    serve12Plus: "Cubes in salads, guacamole with soft dippers, avocado toast with toppings. Let toddler scoop with a spoon.",
    storage: "Ripen on counter; refrigerate once ripe for 2–3 days. Sprinkle cut surface with lemon and wrap tightly to slow browning.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Blueberries", slug: "blueberries", category: "Fruits", emoji: "🫐",
    description: "Tiny antioxidant powerhouses. Always flatten or quarter for babies — whole round blueberries are a choking hazard.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Moderate",
    nutrition: "Antioxidants (anthocyanins), vitamin C, vitamin K, fiber",
    benefits: "Excellent for immune and eye health. The deep blue pigments are potent antioxidants. Great pincer-grasp practice.",
    howToChoose: "Look for plump, dusty-blue berries with a silvery bloom. Avoid shriveled or moldy ones. Frozen wild blueberries are great too.",
    serve69: "Flatten each blueberry with your thumb or the back of a fork, or quarter them. Scatter a few on the tray — do not serve whole or in a bowlful.",
    serve912: "Flattened or halved berries for self-feeding practice. Smash into yogurt or oatmeal for purple power.",
    serve12Plus: "Halved until age 4 for safety (whole round shape is risky). Whole berries only once your child chews reliably — many parents halve until 4.",
    storage: "Refrigerate unwashed up to 2 weeks; wash just before serving. Freeze on a tray then bag for up to 6 months.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Strawberries", slug: "strawberries", category: "Fruits", emoji: "🍓",
    description: "Sweet, fragrant, and packed with vitamin C. Large berries make a great whole-food teether when hulled.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin C, manganese, folate, fiber",
    benefits: "Vitamin C dramatically boosts iron absorption from the same meal — pair strawberries with iron-rich foods. Great for immunity.",
    howToChoose: "Choose deep-red, shiny berries with fresh green caps. Size does not matter much; smell them — fragrant means ripe.",
    serve69: "Hull (remove stem and core) and serve a large whole berry baby can palm and gnaw, or quarter lengthwise into spears.",
    serve912: "Quartered lengthwise or sliced. Mash into yogurt, layer on toast with ricotta, or add to oatmeal.",
    serve12Plus: "Halved or whole small berries. Dip in yogurt or peanut butter. Fun in fruit salads and smoothies.",
    storage: "Refrigerate unwashed 3–7 days. Wash gently before serving. Freeze hulled berries for smoothies.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Raspberries", slug: "raspberries", category: "Fruits", emoji: "🫐",
    description: "Delicate, tart-sweet berries that squish easily. Wonderful finger food — they collapse under light pressure.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Fiber, vitamin C, manganese",
    benefits: "Among the highest-fiber fruits — great for digestion. Tart flavor expands baby's palate beyond sweet.",
    howToChoose: "Plump, dry, deeply colored berries without mush. Use quickly — raspberries spoil faster than other berries.",
    serve69: "Serve whole (they squish easily) or flatten between fingers. Offer 2–3 at a time on the tray.",
    serve912: "Whole berries for pincer practice. Press onto toast with cream cheese or fold into oatmeal.",
    serve12Plus: "By the handful as snacks, in yogurt parfaits, or frozen as refreshing teethers.",
    storage: "Refrigerate 1–3 days max. Freeze in a single layer for smoothies and baking.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Blackberries", slug: "blackberries", category: "Fruits", emoji: "🫐",
    description: "Juicy, sweet-tart berries loaded with fiber. Halve large ones for young babies; they stain — embrace the mess!",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Moderate",
    nutrition: "Fiber, vitamin C, vitamin K, manganese",
    benefits: "Superb fiber content keeps digestion moving. Seeds are harmless. Deep color signals rich antioxidant content.",
    howToChoose: "Shiny, plump, fully black berries (red = unripe and sour). Avoid leaking or moldy containers.",
    serve69: "Halve lengthwise or smash flat. The seeds are safe. Serve a few at a time — they are juicy and slippery.",
    serve912: "Halved berries, smashed into yogurt, or pressed onto pancakes and toast.",
    serve12Plus: "Whole or halved in snacks and salads. Freeze for a cooling summer teether.",
    storage: "Refrigerate 1–3 days. Freeze on a tray for smoothies. Stains wash out best with cold water immediately.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Mango", slug: "mango", category: "Fruits", emoji: "🥭",
    description: "Sunshine-sweet and slippery! A fantastic vitamin A source. The pit makes an excellent gnaw-able teether.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin A, vitamin C, folate",
    benefits: "One of the best vitamin A sources for eye and immune health. Natural sweetness makes it a baby favorite.",
    howToChoose: "Ripe mangoes give slightly at the stem end and smell fruity. Color varies by variety — go by feel and smell.",
    serve69: "Cut long spears with some skin left on the end as a handle (remove skin before eating). Or offer the washed pit to gnaw under supervision.",
    serve912: "Small cubes or spears. Roll slippery pieces in shredded coconut for grip. Mix into yogurt.",
    serve12Plus: "Cubes, mango lassi smoothies, fruit salsa with soft chips. Let toddler scoop cheek halves with a spoon.",
    storage: "Ripen at room temp, then refrigerate 3–5 days. Frozen mango chunks are cheap and perfect for smoothies.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Apple", slug: "apple", category: "Fruits", emoji: "🍎",
    description: "Crisp favorite that must be cooked soft or grated for babies — raw apple chunks are a top choking hazard.",
    introAgeText: "6 months (cooked)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "High (raw)",
    nutrition: "Fiber, vitamin C",
    benefits: "Gentle fiber for digestion. Cooking softens cell walls so babies can manage it safely. Pairs beautifully with cinnamon and nut butters.",
    howToChoose: "Firm, unbruised apples. Sweeter varieties (Fuji, Gala) need no added sugar. Organic if serving skin to older toddlers.",
    serve69: "Steam, bake, or simmer wedges until completely soft and mashable between your fingers. Or grate raw apple finely on a box grater. Never raw chunks.",
    serve912: "Soft-cooked chunks, grated apple mixed into oatmeal or yogurt, or thin steamed slices with peanut butter.",
    serve12Plus: "Very thin raw slices (paper-thin) for confident chewers; continue grating or cooking soft until chewing is reliable. Apple wedges with skin from ~18 months+ with molars.",
    storage: "Whole apples keep weeks in the fridge. Cooked apple refrigerates 3–4 days, freezes well for 3 months.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Pear", slug: "pear", category: "Fruits", emoji: "🍐",
    description: "Buttery when ripe and wonderfully juicy. Ripe pears are soft enough to serve raw in safe shapes.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Fiber, vitamin C, potassium",
    benefits: "Sorbitol and fiber make pears famously helpful for constipation. Gentle, hydrating, and easy to love.",
    howToChoose: "Ripe pears give at the neck. Bartlett turns yellow; Bosc stays brown. Slightly soft = ready.",
    serve69: "Peel and cut very ripe pear into thick spears. If firm, steam until soft. Poach in water with cinnamon for extra softness.",
    serve912: "Peeled spears or cubes. Leave skin on for older babies in this range if chewing well. Great baked with ricotta.",
    serve12Plus: "Wedges with skin for confident chewers, sliced in salads, or baked as a warm dessert with yogurt.",
    storage: "Ripen at room temp stem-up; refrigerate ripe pears 3–5 days. Cooked pear freezes well.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Watermelon", slug: "watermelon", category: "Fruits", emoji: "🍉",
    description: "Ultimate hydrating summer food. Soft, juicy, and easy to gum. Always remove seeds for babies.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Water, vitamin A, vitamin C, lycopene",
    benefits: "Over 90% water — fantastic for hydration. Lycopene supports heart and skin health. Low effort, high joy.",
    howToChoose: "Heavy for its size with a creamy yellow field spot and dull (not shiny) rind. A deep hollow thump suggests ripeness.",
    serve69: "Cut a wide triangular spear with rind left on as a handle (rind off before eating) or seeded cubes. Remove all black seeds.",
    serve912: "Seedless cubes for pincer practice. Freeze cubes lightly for soothing teething snacks.",
    serve12Plus: "Triangles, cubes, frozen pops, or watermelon feta bites for adventurous toddlers.",
    storage: "Whole melon at room temp up to 2 weeks; cut melon refrigerated 3–5 days tightly wrapped.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Orange", slug: "orange", category: "Fruits", emoji: "🍊",
    description: "Vitamin C superstar. Supremes (membrane-free segments) or large sections work best for little mouths.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin C, folate, thiamine, water",
    benefits: "Vitamin C powerfully boosts iron absorption — serve oranges alongside iron-rich meals. Hydrating and refreshing.",
    howToChoose: "Heavy, firm oranges with bright skin. Navel oranges are seedless and easy to segment.",
    serve69: "Serve a large half-wheel slice with peel on as a holder baby gnaws (peel removed before eating), or supreme segments (membrane fully removed) cut in half.",
    serve912: "Supremed segments cut into pieces, or large membrane-free sections. Mix into yogurt.",
    serve12Plus: "Sections with some membrane for chewing practice. Fresh-squeezed (not juice boxes) as an occasional treat.",
    storage: "Counter 1 week or refrigerate 3–4 weeks. Cut segments keep 2–3 days refrigerated.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Peach", slug: "peach", category: "Fruits", emoji: "🍑",
    description: "Juicy, fragrant stone fruit. Ripe peaches slip right off the pit and need only peeling for babies.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin A, vitamin C, potassium, fiber",
    benefits: "Beta-carotene for eyes and immunity. Soft texture is ideal for new eaters. The pit (washed) can be a supervised teether.",
    howToChoose: "Fragrant with a slight give near the stem. Avoid green or rock-hard peaches. Fuzzy skin peels off ripe fruit easily.",
    serve69: "Peel and slice very ripe peach into thick wedges. If firm, halve and bake/steam until soft. Nectarines work identically without peeling fuss.",
    serve912: "Peeled wedges or cubes. Leave skin on wedges for grip (remove before eating). Mix into oatmeal or yogurt.",
    serve12Plus: "Wedges with skin for confident chewers, grilled peach slices, or peach + cottage cheese bowls.",
    storage: "Ripen stem-down at room temp; refrigerate ripe 3–5 days. Sliced peaches freeze beautifully.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Kiwi", slug: "kiwi", category: "Fruits", emoji: "🥝",
    description: "Tangy green gems with more vitamin C than oranges. Tiny black seeds are completely safe.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin C, vitamin K, vitamin E, fiber, folate",
    benefits: "Extraordinary vitamin C for immunity and iron absorption. Actinidin enzyme aids protein digestion. Golden kiwis are sweeter and milder.",
    howToChoose: "Ripe kiwi yields gently to pressure. Rock-hard kiwis are mouth-puckeringly sour — ripen in a paper bag with a banana.",
    serve69: "Halve and scoop flesh with a spoon to serve as mash, or peel and cut into spears. Serve skin-on half as a scoopable cup for older babies.",
    serve912: "Peeled spears, cubes, or scooped mash. The tartness pairs well with sweet yogurt or banana.",
    serve12Plus: "Halved kiwi eaten with a spoon straight from the skin, slices in fruit salads, or frozen kiwi pops.",
    storage: "Ripen at room temp; refrigerate ripe 1–2 weeks. Cut kiwi keeps 2 days covered.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Grapes", slug: "grapes", category: "Fruits", emoji: "🍇",
    description: "Sweet and juicy but the #1 fruit choking hazard. ALWAYS quarter lengthwise for babies and toddlers.",
    introAgeText: "6 months (quartered)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "High (whole)",
    nutrition: "Vitamin K, antioxidants, water",
    benefits: "Hydrating with heart-healthy polyphenols (especially dark grapes). Great pincer-grasp food when cut properly.",
    howToChoose: "Plump grapes firmly attached to green stems. Seedless varieties are easiest. Dark grapes have more antioxidants.",
    serve69: "Quarter LENGTHWISE (never halve crosswise into coins — coins can still block airways). Peel if skin seems tough. Smash flat as an alternative.",
    serve912: "Quartered lengthwise pieces. Still quarter every single grape — no exceptions at this age.",
    serve12Plus: "Continue quartering lengthwise until age 4. Halved lengthwise is acceptable for very confident chewers approaching 4, but quartering is safest.",
    storage: "Refrigerate unwashed 1–2 weeks; wash before serving. Freeze for slushy teething relief (serve slightly thawed, still quartered).",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Cherries", slug: "cherries", category: "Fruits", emoji: "🍒",
    description: "Sweet summer jewels. The pit and round shape make prep essential: always pit and halve.",
    introAgeText: "6 months (pitted)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "High (whole)",
    nutrition: "Vitamin C, potassium, fiber, melatonin",
    benefits: "Natural melatonin may support healthy sleep. Anthocyanins fight inflammation. Sweet-tart flavor builds palate variety.",
    howToChoose: "Firm, glossy, dark cherries with green stems. Darker usually means sweeter.",
    serve69: "Remove pit (use a cherry pitter, straw, or chopstick), halve or quarter. Smash flat for extra safety.",
    serve912: "Pitted halves or quarters. Fold into yogurt or oatmeal. Frozen pitted cherries (thawed) are economical.",
    serve12Plus: "Pitted halves until confident chewing; teach spitting pits only much later (4+). Cherry compote on pancakes is a hit.",
    storage: "Refrigerate unwashed up to 10 days. Pit and freeze for year-round use.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Pineapple", slug: "pineapple", category: "Fruits", emoji: "🍍",
    description: "Tropical, tangy, and tender. Acidity can irritate sensitive skin — watch for redness around the mouth (usually harmless).",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin C, manganese, bromelain",
    benefits: "Bromelain enzyme aids digestion. Manganese supports bone development. Bold flavor expands baby's palate.",
    howToChoose: "Sweet smell at the base, slight give, green fresh-looking crown. Canned in juice (not syrup) is a fine backup.",
    serve69: "Cut spears from ripe, cored pineapple. Core is too fibrous — discard. Tip: a thin smear of coconut oil on cheeks reduces acid irritation.",
    serve912: "Small chunks or spears. Grilled pineapple rings (cooled) are softer and sweeter. Mix into yogurt.",
    serve12Plus: "Rings, chunks, kabobs with other fruit. Pineapple fried rice with soft veggies is a toddler win.",
    storage: "Whole at room temp 2–3 days; cut refrigerated 5–7 days. Frozen chunks perfect for smoothies.",
    isIronRich: false, isProteinRich: false,
  },

  // ---------------- VEGETABLES ----------------
  {
    name: "Broccoli", slug: "broccoli", category: "Vegetables", emoji: "🥦",
    description: "Mini trees babies love to gnaw! Steam or roast until soft — the floret is a perfect built-in handle.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin C, vitamin K, folate, fiber",
    benefits: "More vitamin C than an orange per cup. Sulforaphane compounds support immunity. Bitter notes train adventurous palates.",
    howToChoose: "Tight, dark-green florets with firm stalks. Yellowing means old. Frozen florets are just as nutritious.",
    serve69: "Steam or roast large florets with stems until very soft (easily smashed between fingers). The stem is a natural handle. Serve plain or with olive oil.",
    serve912: "Smaller soft florets, chopped and mixed into pasta, eggs, or cheese melts. Roasted with garlic powder.",
    serve12Plus: "Roasted crispy trees with dips (hummus, yogurt ranch), broccoli cheese bites, stir-fry pieces.",
    storage: "Refrigerate unwashed 3–5 days. Blanch and freeze for long storage. Cooked keeps 3–4 days.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Sweet Potato", slug: "sweet-potato", category: "Vegetables", emoji: "🍠",
    description: "Nature's baby food: sweet, creamy, and loaded with vitamin A. Roast wedges are easy to hold.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin A (beta-carotene), vitamin C, fiber, potassium",
    benefits: "One serving exceeds a baby's daily vitamin A — critical for vision and immunity. Gentle fiber aids digestion.",
    howToChoose: "Firm, heavy sweet potatoes without sprouts or soft spots. Orange flesh has the most vitamin A.",
    serve69: "Roast thick wedges (skin on for grip, remove before eating) at 400°F until very soft. Or mash baked flesh. Even simpler: microwave whole, then scoop.",
    serve912: "Soft cubes, mashed with cinnamon, or spread on toast. Mix into oatmeal for natural sweetness.",
    serve12Plus: "Roasted cubes, sweet potato fries (soft-baked), loaded skins, pancakes, and muffins.",
    storage: "Cool dark place 2–4 weeks (not fridge raw). Cooked keeps 4–5 days refrigerated; freezes well mashed or cubed.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Carrot", slug: "carrot", category: "Vegetables", emoji: "🥕",
    description: "Sweet and vibrant — but must be cooked soft for babies. Raw carrot (including baby carrots) is a serious choking hazard.",
    introAgeText: "6 months (cooked)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "High (raw)",
    nutrition: "Vitamin A (beta-carotene), fiber, vitamin K",
    benefits: "Top source of beta-carotene for eye development. Natural sweetness appeals to new eaters. Roasting caramelizes sugars deliciously.",
    howToChoose: "Firm, bright, smooth carrots. Larger carrots are sweeter than baby carrots. Tops should look fresh if attached.",
    serve69: "Steam, roast, or simmer thick sticks until completely soft and smashable. Grate raw finely as an alternative. Never raw coins or baby carrots.",
    serve912: "Soft coins (steamed/braised until very tender), roasted sticks, or shredded into fritters and muffins.",
    serve12Plus: "Thin raw matchsticks for confident chewers, roasted glazed carrots, or raw sticks with hummus once molars develop (~18mo+).",
    storage: "Refrigerate in a bag 2–4 weeks. Cooked carrots keep 4–5 days; blanch and freeze extras.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Butternut Squash", slug: "butternut-squash", category: "Vegetables", emoji: "🎃",
    description: "Sweet, silky, and easy to roast soft. Pre-cut cubes save serious prep time for busy parents.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin A, vitamin C, fiber, potassium",
    benefits: "Excellent vitamin A for immunity and vision. Soft texture when roasted is ideal for gumming. Mild sweetness wins over new eaters.",
    howToChoose: "Heavy with matte beige skin and no green streaks. Pre-peeled cubes are a worthy shortcut.",
    serve69: "Roast thick half-moons or wedges until very soft and caramelized. Or mash roasted flesh. Halve and roast face-down for easiest scooping.",
    serve912: "Soft cubes, mashed with butter and cinnamon, or blended into mac and cheese sauce for hidden veg.",
    serve12Plus: "Roasted cubes, squash soup with grilled cheese dippers, ravioli filling, or sheet-pan fajita strips.",
    storage: "Whole squash keeps months in cool storage. Cut raw refrigerates 5 days. Cooked keeps 4 days; freezes well.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Peas", slug: "peas", category: "Vegetables", emoji: "🫛",
    description: "Sweet little protein-rich orbs. Flatten for young babies — whole peas can roll toward the airway.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Protein, fiber, iron, vitamin C, vitamin K",
    benefits: "Surprisingly high in plant protein and iron for a vegetable. Frozen peas are flash-frozen at peak nutrition — no shame in frozen!",
    howToChoose: "Frozen petite peas are sweetest and cheapest. Fresh peas in pod are a treat in spring — shell just before cooking.",
    serve69: "Steam until soft then flatten each pea with a fork or your thumb. Or mash into a coarse puree with butter. Scatter flattened peas for practice.",
    serve912: "Slightly flattened or whole soft peas for pincer practice. Smash onto toast with ricotta. Add to pasta and fried rice.",
    serve12Plus: "Whole peas in pastas, soups, and snacks. Fun frozen straight from the bag as a cooling summer snack (for confident chewers).",
    storage: "Frozen peas keep 8–12 months. Cooked peas refrigerate 3–4 days.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Corn", slug: "corn", category: "Vegetables", emoji: "🌽",
    description: "Sweet, sunny, and fun to gnaw. Serve cob strips for babies or cut kernels for older eaters.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Moderate",
    nutrition: "Fiber, B vitamins, vitamin C, antioxidants (lutein)",
    benefits: "Lutein supports eye health. Chewy texture builds oral-motor skills. Undigested kernels in diapers are totally normal!",
    howToChoose: "Fresh ears with green husks and moist silk. Kernels should be plump and milky when pierced. Frozen kernels are excellent.",
    serve69: "Cut a cob into 2-inch wheels or quarter lengthwise into ribs baby can gnaw (kernels stay attached to cob). Or mash kernels into polenta-like mush.",
    serve912: "Cut kernels off the cob and serve (they flatten under gums when cooked soft). Mini cob wheels for practice.",
    serve12Plus: "Half-cobs (corn holders are fun!), kernels in salads and salsas, elote-style with yogurt and lime.",
    storage: "Fresh corn: refrigerate in husk, use within 2–3 days. Cooked kernels keep 3–4 days; freeze well.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Spinach", slug: "spinach", category: "Vegetables", emoji: "🥬",
    description: "Iron-rich greens that wilt into anything. Always cook for babies — raw leaves can stick to the palate.",
    introAgeText: "6 months (cooked)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Iron, folate, vitamin K, vitamin A",
    benefits: "Folate for growth plus plant iron — pair with vitamin C foods to triple absorption. Wilts to nothing in eggs, pasta, and smoothies.",
    howToChoose: "Bright, crisp leaves without slime. Baby spinach is milder. Frozen chopped spinach is cheap and pre-wilted.",
    serve69: "Sauté or steam until fully wilted, chop finely, and mix into mashed potato, eggs, or pasta. Squeeze out excess water. Avoid loose raw leaves.",
    serve912: "Finely chopped cooked spinach in omelets, quesadillas, meatballs, and muffins. Creamed spinach with ricotta.",
    serve12Plus: "Small raw baby leaves in salads for confident chewers, green smoothies, saag-style curries, spanakopita bites.",
    storage: "Refrigerate dry in a towel-lined container 5–7 days. Freeze blanched or buy frozen.",
    isIronRich: true, isProteinRich: false,
  },
  {
    name: "Cauliflower", slug: "cauliflower", category: "Vegetables", emoji: "🥦",
    description: "Mild, mashable, and roasts up sweet. Florets with stems make perfect baby handles.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin C, vitamin K, fiber, choline",
    benefits: "Choline supports brain development. Gentle flavor is great for cautious eaters. Roasting brings out surprising sweetness.",
    howToChoose: "Creamy-white, compact heads without brown spots. Colorful varieties (purple, orange) have extra antioxidants.",
    serve69: "Steam or roast large florets until very soft and easily smashed. Mash with butter as a potato alternative.",
    serve912: "Soft roasted florets with spices, cauliflower cheese, or mashed into pasta sauce.",
    serve12Plus: "Roasted popcorn cauliflower, curry florets, pizza crust experiments, and raw small florets with dip.",
    storage: "Refrigerate whole 1–2 weeks. Cooked keeps 3–4 days. Freezes well after blanching.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Zucchini", slug: "zucchini", category: "Vegetables", emoji: "🥒",
    description: "Mild summer squash that cooks in minutes. Skin is edible and soft when cooked — no peeling needed.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin C, manganese, potassium, water",
    benefits: "Hydrating and gentle — rarely causes fussiness. Absorbs flavors of garlic, cheese, and herbs beautifully.",
    howToChoose: "Small to medium (6–8 inches) — oversized zucchini is watery and seedy. Skin should be glossy and firm.",
    serve69: "Cut into thick spears and steam, roast, or sauté until very soft. Grate raw finely into egg batter for fritters.",
    serve912: "Soft coins, roasted spears with parmesan, shredded into muffins, oats, and meatballs.",
    serve12Plus: "Zucchini boats, fritters, grilled planks, raw matchsticks with dip for confident chewers.",
    storage: "Refrigerate 4–5 days. Cooked keeps 3 days. Shred and freeze for baking.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Tomato", slug: "tomato", category: "Vegetables", emoji: "🍅",
    description: "Juicy and rich in lycopene. Quarter cherry tomatoes — whole ones are choking hazards like grapes.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Moderate",
    nutrition: "Vitamin C, lycopene, potassium, vitamin A",
    benefits: "Cooking multiplies lycopene absorption — tomato sauce is a superfood! Acidity can irritate cheeks; a barrier of oil helps.",
    howToChoose: "Heavy, fragrant tomatoes that yield slightly. Cherry and grape tomatoes are sweetest for babies.",
    serve69: "Quarter cherry tomatoes lengthwise or offer a large wedge of beefsteak tomato. Cook down into sauce. Remove tough skins if they cause gagging.",
    serve912: "Quartered cherries, slow-roasted tomatoes (candy-sweet!), tomato sauce on pasta, bruschetta-style on toast.",
    serve12Plus: "Halved cherries for confident chewers, caprese bites, salsa, and tomato soup with grilled cheese.",
    storage: "Counter until ripe (never fridge whole — kills flavor); refrigerate cut 2–3 days. Sauce freezes 3 months.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Bell Pepper", slug: "bell-pepper", category: "Vegetables", emoji: "🫑",
    description: "Crunchy-sweet vitamin C bombs. Roast until silky for babies — raw is too crunchy for new eaters.",
    introAgeText: "6 months (roasted)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Vitamin C, vitamin A, vitamin B6",
    benefits: "Red peppers have 3x the vitamin C of oranges! Color variety (red, yellow, orange) means varied antioxidants.",
    howToChoose: "Firm, glossy, heavy peppers. Red, orange, and yellow are sweeter than green. Avoid wrinkled skin.",
    serve69: "Roast halved peppers until collapsing and silky; peel charred skin and cut into wide strips. Or steam strips until very soft.",
    serve912: "Soft roasted strips, diced into eggs and pasta, stuffed mini peppers with rice and beans.",
    serve12Plus: "Thin raw strips with hummus, fajita veggies, stuffed pepper cups, and pizza topping.",
    storage: "Refrigerate 1–2 weeks. Roasted strips in oil keep 5 days refrigerated; freeze well.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Green Beans", slug: "green-beans", category: "Vegetables", emoji: "🫛",
    description: "Snappy beans that steam up tender. Whole beans are natural finger food when cooked soft.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Fiber, vitamin C, vitamin K, folate",
    benefits: "Good fiber for digestion plus silicon for growing bones. Fun to hold and gnaw, building hand skills.",
    howToChoose: "Bright, firm beans that snap when bent. Thin haricots verts cook fastest and are most tender.",
    serve69: "Steam or simmer whole beans until very soft and bendy (they should smash easily). Trim hard stem ends. Serve a small pile to grab.",
    serve912: "Soft whole beans or cut pieces. Sauté with garlic and butter, add to stir-fries, or toss with sesame.",
    serve12Plus: "Blanched crunchy-tender beans with dip, green bean fries (breaded and baked), casseroles.",
    storage: "Refrigerate unwashed 5–7 days. Blanch and freeze for 8+ months. Cooked keep 3–4 days.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Cucumber", slug: "cucumber", category: "Vegetables", emoji: "🥒",
    description: "Cool, hydrating, and soothing on teething gums. Peeled spears only — skin and seeds can be tricky.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Water, vitamin K, potassium",
    benefits: "Super hydrating and cooling — a teething favorite. Mild flavor suits cautious eaters. Persian cucumbers are sweetest.",
    howToChoose: "Firm, dark-green, heavy cucumbers. Persian and English (seedless) types are best for babies.",
    serve69: "Peel and cut a thick spear (adult-finger size) with seeds scooped out. Cold from the fridge soothes gums. Grate finely as an alternative.",
    serve912: "Peeled spears or thin half-moons, tzatziki for dipping, cucumber-cream cheese toast.",
    serve12Plus: "Skin-on spears and rounds for confident chewers, quick pickles (low salt), sushi-style rolls.",
    storage: "Refrigerate 1 week. Cut cucumber keeps 2–3 days wrapped. Do not freeze (turns mushy).",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Beets", slug: "beets", category: "Vegetables", emoji: "🫜",
    description: "Earthy-sweet and stunningly pink! Roast until tender. Warning: glorious magenta diapers ahead (totally normal).",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Folate, fiber, potassium, nitrates",
    benefits: "Folate for growth and nitrates for healthy blood flow. Natural sweetness appeals to babies. Golden beets don't stain!",
    howToChoose: "Firm, smooth beets with fresh greens attached (cook the greens too!). Small-medium beets are sweetest.",
    serve69: "Roast whole wrapped in foil until fork-tender, slip skins off, and cut into spears. Or steam peeled wedges until very soft.",
    serve912: "Soft cubes, grated cooked beet into yogurt (pink power!), beet hummus, or mixed into oatmeal.",
    serve12Plus: "Roasted wedges, pickled beets (low sugar), chocolate beet muffins, borscht with sour cream.",
    storage: "Refrigerate unwashed 2–4 weeks (remove greens). Cooked keeps 4–5 days; freezes well.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Eggplant", slug: "eggplant", category: "Vegetables", emoji: "🍆",
    description: "Silky and mild when roasted well. Undercooked eggplant is bitter and spongy — cook it thoroughly.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Fiber, antioxidants (nasunin), potassium",
    benefits: "Nasunin in purple skin protects brain cells. Creamy texture when roasted is perfect for gumming.",
    howToChoose: "Glossy, firm, heavy eggplants. Small Italian or Japanese varieties are sweeter with fewer seeds.",
    serve69: "Roast halved eggplant face-down until collapsing; scoop silky flesh. Or roast thick skin-on wedges until very soft (remove skin before eating).",
    serve912: "Baba ganoush (watch tahini = sesame allergen), roasted cubes in pasta, eggplant parmesan strips.",
    serve12Plus: "Grilled planks, moussaka, caponata on toast, breaded eggplant fries.",
    storage: "Counter 1–2 days or refrigerate up to 5 days. Cooked keeps 3–4 days. Baba ganoush refrigerates 5 days.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Mushrooms", slug: "mushrooms", category: "Vegetables", emoji: "🍄",
    description: "Savory umami that adds depth to baby meals. Always cook thoroughly — never serve raw to babies.",
    introAgeText: "6 months (cooked)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "B vitamins, selenium, vitamin D (if sun-exposed), potassium",
    benefits: "One of few non-animal vitamin D sources. Umami flavor builds savory preferences and makes veggies more appealing.",
    howToChoose: "Firm, dry, unblemished mushrooms. Cremini (baby bella) are flavorful; shiitake caps are meaty. Only store-bought — never foraged for babies.",
    serve69: "Sauté sliced mushrooms in butter/oil until deeply golden and soft. Chop finely and mix into eggs, pasta, or mashed potato.",
    serve912: "Sliced sautéed mushrooms, finely chopped in bolognese, quesadillas, and fried rice.",
    serve12Plus: "Roasted whole caps, mushroom soup, stuffed mushrooms, pizza topping.",
    storage: "Refrigerate in a paper bag 5–7 days (plastic makes them slimy). Cooked keep 3–4 days.",
    isIronRich: false, isProteinRich: false,
  },
];

export const seedFoods2: SeedFood[] = [
  // ---------------- GRAINS ----------------
  {
    name: "Oatmeal", slug: "oatmeal", category: "Grains", emoji: "🥣",
    description: "Creamy, comforting, and endlessly customizable. Iron-fortified infant oatmeal is a top first food.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Iron (if fortified), fiber (beta-glucan), B vitamins",
    benefits: "Iron-fortified oats deliver the #1 nutrient babies need. Beta-glucan fiber feeds healthy gut bacteria. Perfect vehicle for fruits and nut butters.",
    howToChoose: "Iron-fortified infant oatmeal for max iron, or plain rolled oats for the family. Avoid flavored packets (added sugar).",
    serve69: "Cook thick enough to clump on a spoon (thin porridge slides off and frustrates). Pre-load spoons or let baby scoop with hands. Stir in mashed fruit or thinned nut butter.",
    serve912: "Thick oatmeal fingers (spread, chill, slice), overnight oats, oat pancakes. Let baby practice with their own spoon.",
    serve12Plus: "Oatmeal bars, baked oatmeal cups, granola-ish clusters (no whole nuts until 4+), porridge with toppings bar.",
    storage: "Dry oats keep months in an airtight container. Cooked oatmeal refrigerates 4–5 days; add splash of milk when reheating.",
    isIronRich: true, isProteinRich: false,
  },
  {
    name: "Rice", slug: "rice", category: "Grains", emoji: "🍚",
    description: "Soft, bland, and beloved worldwide. Vary grains often — rice can contain arsenic, so don't serve daily.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Energy (carbs), some B vitamins (brown rice has more)",
    benefits: "Gentle and easy to digest. Sticky short-grain rice clumps for easy scooping. A great carrier for iron-rich toppings.",
    howToChoose: "Vary types: basmati and jasmine are lower in arsenic. Rinse well and cook in extra water (6:1) then drain to reduce arsenic.",
    serve69: "Overcooked soft rice pressed into balls or patties, congee (rice porridge) with toppings, or sticky rice clumps. Avoid loose separate grains at first.",
    serve912: "Rice balls (onigiri-style) with fillings, fried rice with soft veggies and egg, rice pudding with fruit.",
    serve12Plus: "Sushi rolls, burrito bowls, risotto, pilaf. Continue varying with quinoa, oats, and barley.",
    storage: "Cool within 1 hour and refrigerate up to 3 days (rice bacteria risk). Reheat steaming hot. Freeze in portions.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Quinoa", slug: "quinoa", category: "Grains", emoji: "🌾",
    description: "Tiny protein-packed seed (a complete protein!). Rinse well to remove bitter coating, then cook fluffy.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Complete protein, iron, magnesium, fiber",
    benefits: "Rare plant food with all essential amino acids. Good iron and magnesium. Tiny grains are great texture exposure.",
    howToChoose: "Pre-rinsed quinoa saves a step (still give a quick rinse). Tri-color is fun for older babies; white is mildest.",
    serve69: "Cook soft (extra water) and mix with mashed avocado, sweet potato, or yogurt so grains clump. Press into soft patties with egg and bake.",
    serve912: "Quinoa patties and balls, mixed into soups and stews, breakfast quinoa porridge with fruit.",
    serve12Plus: "Quinoa salads, stuffed peppers, power bowls, quinoa fried rice.",
    storage: "Dry quinoa keeps 6+ months sealed. Cooked refrigerates 4–5 days; freezes well in portions.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Pasta", slug: "pasta", category: "Grains", emoji: "🍝",
    description: "Slurpable fun and a perfect sauce vehicle. Contains wheat (a top allergen) — introduce like any allergen.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Wheat", containsAllergens: "Wheat (gluten)",
    chokingRisk: "Low",
    nutrition: "Iron (if fortified), B vitamins, energy",
    benefits: "Iron-fortified and legume pastas (chickpea, lentil) add serious nutrition. Fun shapes build eating skills. Batch-cooks brilliantly.",
    howToChoose: "Large shapes for beginners (penne, fusilli, farfalle). Try lentil/chickpea pasta for extra iron and protein. Check for egg if egg-allergic.",
    serve69: "Cook past al dente (very soft). Toss with olive oil or sauce. Large shapes for palming; tiny pastina/stars mixed into sauce for scooping.",
    serve912: "Pasta bakes, spaghetti for slurping practice (cut into short lengths), mac and cheese with hidden veg, pasta salads.",
    serve12Plus: "Any shape with any sauce. Let toddler twirl (messy but skill-building). Cold pasta salads for lunchboxes.",
    storage: "Dry pasta keeps 1–2 years. Cooked refrigerates 3–5 days tossed with oil; freeze sauced portions.",
    isIronRich: true, isProteinRich: false,
  },
  {
    name: "Bread", slug: "bread", category: "Grains", emoji: "🍞",
    description: "Toast is a baby-led weaning hero. Lightly toast strips so they don't gum into a sticky ball.",
    introAgeText: "6 months (toasted)", introAgeMonths: 6, isAllergen: true, allergenName: "Wheat", containsAllergens: "Wheat (gluten); often soy, sesame, dairy",
    chokingRisk: "Low",
    nutrition: "Iron (if fortified), B vitamins, fiber (whole grain)",
    benefits: "Perfect vehicle for nutrient-dense toppings: nut butters, avocado, hummus, ricotta. Whole grain adds fiber.",
    howToChoose: "Whole grain, low-sodium bread. Check labels for sesame (now a major allergen) and honey (unsafe under 12 months).",
    serve69: "Lightly toast strips (toast should be golden-crisp outside, not doughy). Top with thin nut butter, mashed avocado, or hummus. Avoid untoasted soft bread which balls up.",
    serve912: "Toast fingers with toppings, French toast strips (egg + milk), grilled cheese strips, panzanella-style salads.",
    serve12Plus: "Sandwiches (cut appropriately), toast bar with toppings, homemade pizza on toast, bread pudding.",
    storage: "Counter 3–5 days, fridge extends (but dries). Freeze sliced — toast straight from frozen.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Barley", slug: "barley", category: "Grains", emoji: "🌾",
    description: "Chewy, nutty ancient grain for soups and stews. Contains gluten — introduce like other wheat-family grains.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "Gluten (not wheat, but related)",
    chokingRisk: "Low",
    nutrition: "Fiber (beta-glucan), selenium, B vitamins, iron",
    benefits: "Exceptional fiber for digestion. Hearty texture teaches chewing. Wonderful in soups where it plumps soft.",
    howToChoose: "Pearl barley cooks fastest and softest. Hulled barley is more nutritious but chewier — save for toddlers.",
    serve69: "Simmer pearl barley until very soft and porridge-like. Mash slightly and mix with fruit or veg puree. Add to soups.",
    serve912: "Soft barley in stews and soups, barley porridge with cinnamon and fruit, mixed grain patties.",
    serve12Plus: "Mushroom barley soup, grain bowls, risotto-style barley, cold salads.",
    storage: "Dry barley keeps 1+ year sealed. Cooked refrigerates 4–5 days; freezes well.",
    isIronRich: false, isProteinRich: false,
  },

  // ---------------- PROTEINS ----------------
  {
    name: "Chicken", slug: "chicken", category: "Proteins", emoji: "🍗",
    description: "Lean, mild, and versatile. Dark meat has more iron — don't fear the thigh! Keep it moist to prevent dryness.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Protein, iron, zinc, B vitamins (B6, B12)",
    benefits: "Heme iron (easily absorbed) plus zinc for immunity. Dark meat has 2x the iron of breast. Mild flavor accepts any seasoning.",
    howToChoose: "Bone-in thighs are juiciest and cheapest. Any cut works — moisture matters more than cut. Cook to 165°F.",
    serve69: "Offer a whole drumstick with skin and cartilage removed (great handle!), or slow-cooked shredded thigh. Mince finely into sauce. Avoid dry diced breast.",
    serve912: "Shredded or minced in pasta, quesadillas, and fried rice. Ground chicken meatballs and patties. Slow-cooker pulled chicken.",
    serve12Plus: "Strips, nuggets (homemade baked), skewers, chicken soup, curry pieces. Teach biting from a held piece.",
    storage: "Refrigerate cooked 3–4 days. Freeze shredded in broth (stays moist) up to 3 months.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Beef", slug: "beef", category: "Proteins", emoji: "🥩",
    description: "The iron champion of baby foods. Slow-cooked shreds and meatballs are perfect textures for beginners.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Iron (heme), zinc, protein, vitamin B12",
    benefits: "Best-absorbed iron of any food — critical after 6 months when stores deplete. Zinc and B12 for growth and brain development.",
    howToChoose: "Chuck roast for shredding, ground beef (80/20 stays moist) for balls. Grass-fed has slightly more omega-3s.",
    serve69: "Slow-cook a large strip of chuck until shreddable, or offer a big bone-free rib to gnaw and suck (iron-rich juices!). Mini meatballs with grated veg. Cook ground beef to 160°F.",
    serve912: "Meatballs, meatloaf fingers, slow-cooked shredded beef in sauce, bolognese. Ground beef crumbles in pasta.",
    serve12Plus: "Tender strips of steak (cut against grain, bite-size), burgers, kebabs, tacos, shepherd's pie.",
    storage: "Cooked beef refrigerates 3–4 days. Freeze meatballs and shreds in sauce up to 3 months.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Turkey", slug: "turkey", category: "Proteins", emoji: "🦃",
    description: "Lean, mild, and budget-friendly ground. Like chicken, dark meat brings more iron to the table.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Protein, iron, zinc, selenium, B vitamins",
    benefits: "Selenium for thyroid health plus heme iron. Mild taste works in any cuisine. Ground turkey is endlessly versatile.",
    howToChoose: "Ground thigh meat stays juiciest. Whole bone-in thighs for shredding. Cook to 165°F.",
    serve69: "Slow-cooked shredded thigh, mini meatballs with sweet potato binder, or finely minced in sauce. Keep textures moist — turkey dries fast.",
    serve912: "Meatballs, patties, turkey bolognese, quesadillas, meatloaf muffins.",
    serve12Plus: "Burgers, tacos, meatballs on skewers, turkey chili (mild), deli slices (low-sodium, watch nitrates).",
    storage: "Cooked refrigerates 3–4 days. Freeze meatballs and patties up to 3 months.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Lamb", slug: "lamb", category: "Proteins", emoji: "🍖",
    description: "Rich, iron-dense red meat with a distinctive flavor that builds adventurous palates early.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Iron (heme), zinc, protein, B12",
    benefits: "Comparable iron to beef with a unique flavor profile. Early exposure to varied flavors reduces pickiness later.",
    howToChoose: "Shoulder or leg for slow cooking; ground lamb for kofta. Trim excess fat but keep some for moisture.",
    serve69: "Slow-cook shoulder until shreddable, or offer a large bone-free strip to gnaw. Mini lamb meatballs with mint and yogurt.",
    serve912: "Meatballs, shredded in tomato sauce, shepherd's pie, mild curry pieces.",
    serve12Plus: "Kofta skewers, lamb burgers, chops (cut from bone), gyro-style pitas.",
    storage: "Cooked refrigerates 3–4 days. Freeze shreds and meatballs up to 3 months.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Pork", slug: "pork", category: "Proteins", emoji: "🥓",
    description: "Mild, tender, and rich in thiamine. Slow-cooked shoulder pulls apart into perfect baby shreds.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Protein, thiamine (B1), iron, zinc, B6",
    benefits: "Top source of thiamine for energy metabolism. Tenderloin is as lean as chicken breast. Takes on any flavor.",
    howToChoose: "Shoulder/butt for shredding; tenderloin for quick cooking. Cook whole cuts to 145°F + 3 min rest; ground to 160°F.",
    serve69: "Slow-cooked pulled shoulder, finely minced in sauce, or a large tender strip to gnaw. Keep moist with cooking juices.",
    serve912: "Pulled pork, mini meatballs, tenderloin medallions (cut small), carnitas-style crispy bits (soft inside).",
    serve12Plus: "Tenderloin slices, pork fried rice, dumplings, tacos al pastor (mild). Avoid processed ham/bacon as staples (sodium, nitrates).",
    storage: "Cooked refrigerates 3–4 days. Freeze pulled pork in juices up to 3 months.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Salmon", slug: "salmon", category: "Proteins", emoji: "🍣",
    description: "Brain-building omega-3 superstar. Contains fish (top allergen) — introduce early and serve weekly.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Fish", containsAllergens: "Fish",
    chokingRisk: "Low",
    nutrition: "Omega-3 DHA, vitamin D, protein, B12",
    benefits: "DHA is literally brain-building material. Vitamin D (rare in food!) plus top-quality protein. Low mercury — safe weekly.",
    howToChoose: "Wild sockeye or responsibly farmed Atlantic. Fresh should smell like the ocean, not fishy. Canned (boneless, low-sodium) is great.",
    serve69: "Bake until it flakes easily (145°F); check meticulously for bones. Flake into small moist pieces or mash with avocado. Salmon patties with egg binder.",
    serve912: "Flaked into pasta, salmon patties, mixed into fried rice, salmon + sweet potato cakes.",
    serve12Plus: "Baked fillets, teriyaki bites, fish tacos, sushi-style rolls (fully cooked fish for toddlers).",
    storage: "Fresh: use within 1–2 days refrigerated. Cooked keeps 3 days. Freeze up to 2–3 months.",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "White Fish (Cod)", slug: "white-fish-cod", category: "Proteins", emoji: "🐟",
    description: "Delicately mild and flaky — the gentlest fish intro. Contains fish allergen; bones need careful checking.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Fish", containsAllergens: "Fish",
    chokingRisk: "Low",
    nutrition: "Protein, vitamin B12, selenium, iodine",
    benefits: "Lean protein with iodine for thyroid and brain development. Mild flavor rarely rejected. Flakes into perfect soft pieces.",
    howToChoose: "Cod, haddock, pollock, halibut, tilapia all work. Firm, translucent flesh with ocean smell. Frozen fillets are excellent.",
    serve69: "Steam or bake until opaque and flaky (145°F). Press between fingers to find bones. Flake finely and mix with mashed potato or avocado.",
    serve912: "Fish cakes, flaked into pasta and chowders, breaded baked fish fingers (homemade).",
    serve12Plus: "Baked fish sticks, fish tacos, parchment-baked packets, fish pie.",
    storage: "Fresh: use within 1–2 days. Cooked keeps 3 days refrigerated. Freeze up to 3 months.",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "Sardines", slug: "sardines", category: "Proteins", emoji: "🐟",
    description: "Tiny fish, massive nutrition: omega-3s, calcium, and iron in one cheap can. Mash bones and all (they're soft!).",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Fish", containsAllergens: "Fish",
    chokingRisk: "Low",
    nutrition: "Omega-3 DHA, calcium, iron, vitamin D, B12",
    benefits: "Perhaps the most nutritious baby food per penny: bones = calcium, flesh = DHA + iron. Very low mercury (small fish).",
    howToChoose: "Canned in water or olive oil, low-sodium, boneless/skinless for easiest prep (bones in regular cans are safe when mashed but start boneless).",
    serve69: "Mash with avocado or sweet potato and spread on toast. Mix into tomato pasta sauce (melts invisibly). Sardine + potato patties.",
    serve912: "Mashed on toast soldiers, mixed into fried rice, sardine toast with lemon, pasta with sardine-tomato sauce.",
    serve12Plus: "Whole fillets on crackers with cream cheese, Mediterranean toast, Caesar-style salads (egg-free dressing).",
    storage: "Unopened cans keep years. Opened: transfer to glass, refrigerate, use within 2 days.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Tuna", slug: "tuna", category: "Proteins", emoji: "🐟",
    description: "Pantry staple with staying power. Choose light/skipjack (lower mercury) and limit albacore for babies.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Fish", containsAllergens: "Fish",
    chokingRisk: "Low",
    nutrition: "Protein, omega-3s, selenium, B12, vitamin D",
    benefits: "Convenient protein with real omega-3s. Selenium protects against mercury. Shelf-stable for emergency meals.",
    howToChoose: "Light/skipjack canned in water, low-sodium. Limit albacore/white tuna (higher mercury) to occasional servings.",
    serve69: "Drain and mash finely with avocado, yogurt, or olive oil. Mix into sweet potato mash. Tuna + white bean patties.",
    serve912: "Tuna melts (open-faced, low-sodium cheese), tuna pasta bake, onigiri filling, tuna salad with yogurt.",
    serve12Plus: "Sandwiches, tuna cakes, niçoise-style bowls, tuna noodle casserole.",
    storage: "Unopened cans keep 2–5 years. Opened: refrigerate in glass, use within 2 days.",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "Shrimp", slug: "shrimp", category: "Proteins", emoji: "🍤",
    description: "Sweet, quick-cooking shellfish. Contains shellfish allergen — introduce early. Must be minced (rubbery texture!).",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Shellfish", containsAllergens: "Shellfish",
    chokingRisk: "Moderate",
    nutrition: "Protein, iodine, selenium, B12, choline",
    benefits: "Iodine for brain development plus lean protein. Cooks in minutes. Sweet flavor appeals to babies.",
    howToChoose: "Wild-caught when possible. Fresh should smell briny-sweet. Frozen raw shrimp (thaw overnight) are often fresher than 'fresh'.",
    serve69: "Cook until pink and firm (145°F), then mince VERY finely or blend into patties — whole shrimp are too rubbery. Mix minced shrimp into congee or mashed potato.",
    serve912: "Finely chopped in fried rice and pasta, shrimp cakes, minced in dumplings and spring rolls (soft).",
    serve12Plus: "Butterflied and flattened (easier to chew), chopped in tacos and pasta, shrimp scampi-style with soft bread.",
    storage: "Fresh: use within 1–2 days. Cooked keeps 3 days. Freeze raw or cooked up to 3 months.",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "Tofu", slug: "tofu", category: "Proteins", emoji: "🍲",
    description: "Soft, mild soy protein that absorbs any flavor. Contains soy allergen. Firm/extra-firm holds together best.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Soy", containsAllergens: "Soy",
    chokingRisk: "Low",
    nutrition: "Protein, calcium (if set with calcium sulfate), iron",
    benefits: "Complete plant protein with calcium for bones. Silken blends into smoothies; firm crisps for finger food. Budget superstar.",
    howToChoose: "Firm or extra-firm for finger food; silken for blending. Check label: calcium-set (calcium sulfate) has far more calcium.",
    serve69: "Cut firm tofu into adult-finger strips; pan-fry or bake until golden outside (easier to grip, soft inside). Crumble silken into oatmeal. No need to press for babies.",
    serve912: "Baked tofu cubes, scrambled (crumbled + turmeric), mapo-style soft tofu, blended into smoothies and pasta sauce.",
    serve12Plus: "Crispy baked cubes with dips, stir-fry pieces, tofu nuggets, miso soup cubes (low-sodium miso).",
    storage: "Unopened refrigerated to date. Opened: submerge in fresh water, change daily, use in 3–5 days. Freeze for chewier texture.",
    isIronRich: true, isProteinRich: true,
  },

  // ---------------- DAIRY & EGGS ----------------
  {
    name: "Egg", slug: "egg", category: "Dairy & Eggs", emoji: "🥚",
    description: "Nutritional powerhouse with brain-building choline. Top allergen — early introduction is now recommended.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Egg", containsAllergens: "Egg",
    chokingRisk: "Low",
    nutrition: "Choline, protein, iron, B12, vitamin D, healthy fats",
    benefits: "Egg yolk is one of the best choline sources — essential for memory development. Early intro (around 6 months) may reduce egg allergy risk.",
    howToChoose: "Any fresh eggs; pasture-raised have more omega-3s and vitamin D. Check dates; do a float test if unsure (sinkers = fresh).",
    serve69: "Hard-boil and mash yolk + white with avocado or yogurt (serve both together — separating is outdated advice). Or offer a halved hard-boiled egg. Fully cook: no runny yolks for babies.",
    serve912: "Scrambled strips, omelet fingers with fillings, egg cups with veggies, French toast sticks.",
    serve12Plus: "Fried (fully set), egg sandwiches, frittata wedges, breakfast burritos, egg salad (finely chopped).",
    storage: "Refrigerate 3–5 weeks (US washed eggs must stay cold). Hard-boiled (peeled) keep 1 week. Cooked egg dishes 3–4 days.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Yogurt", slug: "yogurt", category: "Dairy & Eggs", emoji: "🍦",
    description: "Creamy, tangy probiotic food. Choose whole-milk PLAIN — baby yogurts are often sugary marketing.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Dairy", containsAllergens: "Cow's milk",
    chokingRisk: "Low",
    nutrition: "Calcium, protein, probiotics, B12, iodine",
    benefits: "Probiotics support gut and immune health. Whole-milk fat fuels brain growth. Fermentation makes it gentler than milk.",
    howToChoose: "Whole-milk PLAIN yogurt with live cultures. Greek = more protein; regular = milder. Avoid honey flavors (under 12mo) and high sugar.",
    serve69: "Pre-load spoons and lay on the tray (let baby self-feed!). Swirl in fruit puree, nut butter, or cinnamon. Dollop on oatmeal. Full-fat only.",
    serve912: "Yogurt bowls with soft fruit, frozen yogurt drops (piped + frozen), smoothies, tzatziki with soft dippers.",
    serve12Plus: "Parfaits, yogurt bark (frozen with fruit), raita with curry, overnight oats base.",
    storage: "Refrigerate to date; use opened within 5–7 days. Freezes well in portions (texture changes — best for smoothies).",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "Cheese", slug: "cheese", category: "Dairy & Eggs", emoji: "🧀",
    description: "Calcium-rich and beloved. Choose low-sodium varieties and avoid honey-flavored or mold-ripened for babies.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Dairy", containsAllergens: "Cow's milk (or goat/sheep)",
    chokingRisk: "Low",
    nutrition: "Calcium, protein, vitamin A, B12, phosphorus",
    benefits: "Concentrated calcium and protein in tiny servings. Hard cheeses are lower in lactose. Great vehicle for whole grains and veggies.",
    howToChoose: "Low-sodium: Swiss, fresh mozzarella, ricotta, mascarpone. Avoid: high-sodium halloumi/feta as staples, blue/brie (mold), processed singles.",
    serve69: "Thinly shredded (thick cubes are risky), melted on toast strips, or ricotta spread thick. Grate over pasta and eggs. Serve pasteurized only.",
    serve912: "Shredded, melted quesadillas, cheese + bean pinwheels, cottage cheese with fruit (low-sodium).",
    serve12Plus: "Cubes for confident chewers, cheese boards with fruit, homemade pizza, mac and cheese with hidden veg.",
    storage: "Refrigerate wrapped; hard cheese 3–4 weeks, fresh mozzarella 3–5 days. Grate and freeze for cooking.",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "Whole Milk (as a drink)", slug: "whole-milk-drink", category: "Dairy & Eggs", emoji: "🥛",
    description: "As a DRINK only from 12 months — but cooking with milk and dairy foods are fine from 6 months.",
    introAgeText: "12 months (as drink)", introAgeMonths: 12, isAllergen: true, allergenName: "Dairy", containsAllergens: "Cow's milk",
    chokingRisk: "Low",
    nutrition: "Calcium, protein, vitamin D (if fortified), B12",
    benefits: "After 12 months, milk supports bone growth — but limit to ~16oz/day since excess displaces iron-rich foods and can cause anemia.",
    howToChoose: "Whole milk until age 2 (brain needs the fat), then per pediatrician. Fortified with vitamin D. No raw milk for children.",
    serve69: "NOT as a drink — breastmilk/formula remains the milk. But DO cook with milk: oatmeal, mashed potato, sauces, pancakes, yogurt, and cheese are all encouraged.",
    serve912: "Same: milk IN foods (custards, sauces, baked goods) is great; milk AS the drink waits until 12 months. Keep offering dairy foods for calcium.",
    serve12Plus: "Introduce as a drink in an open cup (not bottle) with meals — max ~16oz/day. Offer water between meals. Continue iron-rich foods daily.",
    storage: "Refrigerate at 38–40°F; use within 5–7 days of opening. Freeze in portions (shake after thawing).",
    isIronRich: false, isProteinRich: true,
  },

  // ---------------- BEANS & LEGUMES ----------------
  {
    name: "Lentils", slug: "lentils", category: "Beans & Legumes", emoji: "🍲",
    description: "The easiest legume: no soaking, cooks in 20 minutes, and red lentils melt into creamy dal.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Iron, protein, folate, fiber",
    benefits: "Top plant iron source with folate for growth. Red lentils dissolve into perfect baby texture. Pair with vitamin C to boost iron absorption 3x.",
    howToChoose: "Red lentils for creamy (best for babies), brown/green hold shape. Rinse well; pick out any stones.",
    serve69: "Simmer red lentils until completely broken down (dal-style). Spread thick on toast, mix with rice, or thin into soup. Brown lentils: mash well.",
    serve912: "Lentil bolognese, patties and balls, soups and stews, lentil + veggie muffins.",
    serve12Plus: "Tacos with lentil filling, curries, salads, sloppy joes (lentil-based).",
    storage: "Dry lentils keep 1+ year. Cooked refrigerate 4–5 days; freeze in portions 3 months.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Black Beans", slug: "black-beans", category: "Beans & Legumes", emoji: "🫘",
    description: "Creamy, iron-rich, and dirt cheap. Flatten each bean for babies — whole beans are the perfect choking size.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Moderate",
    nutrition: "Iron, protein, fiber, folate",
    benefits: "Excellent iron and fiber. Skins are safe. Canned (rinsed well) are just as nutritious and save hours.",
    howToChoose: "Low-sodium canned (rinse thoroughly) or dried cooked until very soft. Beans should smash easily between fingers.",
    serve69: "Flatten each bean with a fork or your thumb, or mash into refried-style spread. Mix mashed beans into sweet potato or avocado. Never whole at this age.",
    serve912: "Slightly smashed or whole soft beans for pincer practice. Black bean + corn cakes, quesadillas, brownie bites (yes, really).",
    serve12Plus: "Whole beans in tacos, burritos, chili, and salads. Crispy roasted beans as snacks for confident chewers.",
    storage: "Cooked/canned (transferred to glass) refrigerate 3–4 days. Freeze in portions 3 months.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Chickpeas", slug: "chickpeas", category: "Beans & Legumes", emoji: "🫘",
    description: "Nutty and versatile. Rub skins off and smash for babies — skins can cause gagging (harmless but annoying).",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Moderate",
    nutrition: "Protein, fiber, iron, folate",
    benefits: "Great protein and fiber. Aquafaba (can liquid) whips like egg whites for allergy baking. Roast into crunchy snacks for toddlers.",
    howToChoose: "Low-sodium canned (rinse well) or dried cooked very soft. Squeeze: they should squish easily.",
    serve69: "Pinch skins off, then smash flat or mash into hummus-like spread (without tahini at first if tracking sesame separately). Mix into mashed veg.",
    serve912: "Smashed or halved for pincer practice. Chickpea patties, pasta with chickpeas, mild chana masala.",
    serve12Plus: "Roasted crispy chickpeas, whole in salads and curries, cookie dough hummus (chickpea-based dessert dip).",
    storage: "Cooked refrigerate 3–4 days. Freeze whole or as hummus 3 months.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Hummus", slug: "hummus", category: "Beans & Legumes", emoji: "🫘",
    description: "Creamy chickpea-tahini dip. Contains sesame (top allergen via tahini) — great for allergen exposure.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Sesame", containsAllergens: "Sesame (tahini)",
    chokingRisk: "Low",
    nutrition: "Protein, fiber, healthy fats, iron",
    benefits: "Double nutrition: chickpeas + sesame. Perfect dip to make vegetables exciting. Store-bought is fine (check sodium).",
    howToChoose: "Plain classic hummus. Check sodium (lower is better); avoid honey or spicy varieties for babies.",
    serve69: "Spread THINLY on toast strips or banana — never a big glob (sticky texture). Thin with water, lemon, or olive oil. Use as a sauce on pasta.",
    serve912: "Thin spread on everything, dip for soft-cooked veg, pasta sauce thinned with water, sandwich spread.",
    serve12Plus: "Dip for raw veg, pita pockets, hummus pasta, flavored varieties (roasted red pepper, beet).",
    storage: "Refrigerate 5–7 days (homemade 4–5). Freeze in portions 3 months; stir well after thawing.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Edamame", slug: "edamame", category: "Beans & Legumes", emoji: "🫛",
    description: "Sweet young soybeans with complete protein. Smash for babies — whole pods are for older kids only.",
    introAgeText: "6 months (shelled)", introAgeMonths: 6, isAllergen: true, allergenName: "Soy", containsAllergens: "Soy",
    chokingRisk: "Moderate",
    nutrition: "Complete protein, iron, folate, vitamin K",
    benefits: "One of few complete plant proteins. Sweet flavor appeals to babies. Frozen shelled edamame cooks in 5 minutes.",
    howToChoose: "Frozen shelled (mukimame) — easiest. Pods in shell are a choking hazard for babies; buy shelled only.",
    serve69: "Steam shelled beans until soft, then smash each flat or mash into spread. Mix into mashed potato or avocado.",
    serve912: "Smashed or halved for practice. Edamame + corn succotash, blended into pesto (nut-free), fried rice.",
    serve12Plus: "Whole beans as snacks, in salads and bowls. Teach pod-popping only at 4+ (pods are choking hazards).",
    storage: "Frozen keeps 8–12 months. Cooked refrigerate 3–4 days. Cold leftover edamame makes great lunchbox protein.",
    isIronRich: true, isProteinRich: true,
  },

  // ---------------- NUTS & SEEDS ----------------
  {
    name: "Peanut Butter", slug: "peanut-butter", category: "Nuts & Seeds", emoji: "🥜",
    description: "Top allergen to introduce EARLY (around 6 months, even 4–6 with pediatrician guidance). Never whole peanuts before age 4.",
    introAgeText: "6 months (thinned)", introAgeMonths: 6, isAllergen: true, allergenName: "Peanut", containsAllergens: "Peanut",
    chokingRisk: "High (whole nuts)",
    nutrition: "Protein, healthy fats, vitamin E, niacin",
    benefits: "Landmark LEAP study: early peanut introduction reduces peanut allergy by 81%! Serve 2g peanut protein 3x/week once introduced.",
    howToChoose: "Natural style: peanuts + salt only. No honey-roasted (honey unsafe under 12mo). Stirred drippy kinds thin most easily.",
    serve69: "MUST thin: mix 2 tsp peanut butter with water, breastmilk, or warm oatmeal until drippy. Or spread paper-thin on toast. Never a spoonful or glob (choking hazard). Start with 1/4 tsp mixed in food, watch 10 min.",
    serve912: "Thin spread on toast, stirred into oatmeal and smoothies, peanut noodles (thin sauce), energy balls (mashed, no whole nuts).",
    serve12Plus: "Normal spreads and sandwiches, satay-style sauces, African peanut stew (mild). Still no whole peanuts until age 4+.",
    storage: "Natural PB: refrigerate after opening (or cool pantry if used fast). Lasts 3–6 months opened.",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "Almond Butter", slug: "almond-butter", category: "Nuts & Seeds", emoji: "🥜",
    description: "Tree nut exposure in a jar. Introduce like peanut: thinned, early, and regularly. Never whole almonds before 4.",
    introAgeText: "6 months (thinned)", introAgeMonths: 6, isAllergen: true, allergenName: "Tree Nuts", containsAllergens: "Tree nuts (almond)",
    chokingRisk: "High (whole nuts)",
    nutrition: "Vitamin E, healthy fats, calcium, protein",
    benefits: "Vitamin E for immune health plus calcium. Each tree nut is a distinct exposure — rotate almond, cashew, walnut butters.",
    howToChoose: "Ingredients: almonds (+ salt). Avoid added sugar, palm oil, honey. Drippy natural style thins best.",
    serve69: "Thin with water/milk until drippy, or spread paper-thin on toast. Stir thinned butter into oatmeal or yogurt. Introduce on a separate day from peanut to track reactions.",
    serve912: "Thin spreads, stirred into porridge, drizzled (thinned) over pancakes, almond-crusted baked foods (finely ground).",
    serve12Plus: "Sandwiches, smoothies, sauces, baking. Whole almonds only at 4+.",
    storage: "Refrigerate natural almond butter; use within 3–6 months. Stir before each use.",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "Cashew Butter", slug: "cashew-butter", category: "Nuts & Seeds", emoji: "🥜",
    description: "Creamiest nut butter — blends invisibly into sauces. Tree nut allergen; introduce separately from other nuts.",
    introAgeText: "6 months (thinned)", introAgeMonths: 6, isAllergen: true, allergenName: "Tree Nuts", containsAllergens: "Tree nuts (cashew)",
    chokingRisk: "High (whole nuts)",
    nutrition: "Healthy fats, iron, zinc, magnesium",
    benefits: "Notably high in iron and zinc for a nut butter. Ultra-creamy texture blends into anything — the stealth nutrition champ.",
    howToChoose: "Cashews + salt only. Raw vs roasted both fine. Avoid honey-roasted and chocolate varieties for babies.",
    serve69: "Thin until drippy and stir into oatmeal, yogurt, or purees. Paper-thin on toast. Blend into pasta sauce for creaminess without dairy.",
    serve912: "Sauces (dairy-free alfredo!), spreads, smoothies, energy bites (mashed soft).",
    serve12Plus: "Sandwiches, curry sauces, homemade vegan cheese sauces, baking. Whole cashews only at 4+.",
    storage: "Refrigerate after opening; 3–6 months. Oil separation is normal — stir well.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Tahini", slug: "tahini", category: "Nuts & Seeds", emoji: "🫘",
    description: "Sesame seed butter — the allergen hiding in hummus. Calcium-rich and perfect thinned into sauces.",
    introAgeText: "6 months (thinned)", introAgeMonths: 6, isAllergen: true, allergenName: "Sesame", containsAllergens: "Sesame",
    chokingRisk: "Low",
    nutrition: "Calcium, healthy fats, iron, zinc",
    benefits: "Outstanding calcium for bones. Sesame is now a top-9 allergen — deliberate early exposure matters. Makes everything creamy.",
    howToChoose: "100% ground sesame (hulled is milder; unhulled has more calcium but bitter). Runny, pourable tahini is freshest.",
    serve69: "Thin with water/lemon until drippy; stir into oatmeal, yogurt, or mashed sweet potato. Paper-thin on toast. Start with 1/4 tsp, watch for reactions.",
    serve912: "Thinned drizzles, hummus (homemade = sodium control), tahini-banana toast, noodles with tahini sauce.",
    serve12Plus: "Dressings, halva treats (low sugar), tahini cookies, sesame noodles, baba ganoush.",
    storage: "Pantry 6+ months (oil separates — stir). Refrigeration extends but thickens; warm to loosen.",
    isIronRich: true, isProteinRich: false,
  },
  {
    name: "Chia Seeds", slug: "chia-seeds", category: "Nuts & Seeds", emoji: "🌱",
    description: "Omega-3 rich seeds that gel in liquid. NEVER dry by the spoonful — they expand and can block airways. Always soak.",
    introAgeText: "6 months (soaked)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Moderate (dry)",
    nutrition: "Omega-3 ALA, fiber, calcium, iron",
    benefits: "Top plant omega-3 plus more calcium per gram than milk. Gel texture is fun sensory play. Great egg replacer in baking.",
    howToChoose: "Black or white (identical nutrition). Whole seeds last longer than ground. No need for organic premium.",
    serve69: "Soak 1 tbsp in 4 tbsp liquid 15+ min until fully gelled, then stir into yogurt or oatmeal. Or bake into muffins/pancakes. Never serve dry seeds or dry sprinkles at this age.",
    serve912: "Chia pudding cups with fruit, soaked stirred into anything, baked into oat cups and breads.",
    serve12Plus: "Chia pudding parfaits, jam (chia + mashed fruit), smoothies, crackers with baked-in chia.",
    storage: "Dry seeds keep 2+ years sealed in pantry. Soaked gel refrigerates 5 days. Chia pudding 4–5 days.",
    isIronRich: true, isProteinRich: false,
  },
  {
    name: "Flaxseed", slug: "flaxseed", category: "Nuts & Seeds", emoji: "🌱",
    description: "Omega-3 and fiber booster — but must be GROUND (whole seeds pass straight through undigested).",
    introAgeText: "6 months (ground)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Omega-3 ALA, fiber, lignans",
    benefits: "Excellent fiber for constipation plus anti-inflammatory omega-3s. Ground flax + water = vegan egg replacer (1 tbsp + 3 tbsp water).",
    howToChoose: "Buy whole and grind fresh (coffee grinder) — pre-ground goes rancid fast. Golden or brown are equal.",
    serve69: "Stir 1 tsp ground flax into oatmeal, yogurt, or purees. Bake into pancakes and muffins. Store ground flax in the freezer.",
    serve912: "Mixed into everything bready and porridge-y. Flax eggs in baking. Sprinkle (ground) on toast with nut butter.",
    serve12Plus: "Smoothies, homemade granola bars, breading for baked foods, energy balls.",
    storage: "Whole seeds: pantry 1 year. Ground: freezer 3–6 months (goes rancid at room temp in weeks).",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Coconut", slug: "coconut", category: "Nuts & Seeds", emoji: "🥥",
    description: "Tropical fats and fiber. Labeled as tree nut in the US, but true coconut allergy is very rare.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "Labeled as tree nut (FDA) — allergy rare",
    chokingRisk: "Low",
    nutrition: "Healthy fats (MCTs), fiber, manganese",
    benefits: "MCT fats are easily digested energy. Coconut milk makes dairy-free curries creamy. Unsweetened shreds add texture.",
    howToChoose: "Unsweetened shredded coconut; full-fat canned coconut milk (no guar gum issues for babies). Avoid sweetened flakes.",
    serve69: "Simmer foods in coconut milk (curries, oatmeal). Use finely shredded unsweetened coconut as a grip coating on slippery fruits. Coconut yogurt (check sugar).",
    serve912: "Coconut milk curries and soups, shredded in baking, coconut-crusted baked chicken (finely shredded).",
    serve12Plus: "Fresh young coconut flesh (soft), coconut chips (thin, supervised), piña-style smoothies, coconut rice.",
    storage: "Shredded: pantry 6 months sealed. Opened coconut milk: refrigerate 4–5 days; freeze leftovers in ice cube trays.",
    isIronRich: false, isProteinRich: false,
  },

  // ---------------- FLAVOR & FATS ----------------
  {
    name: "Garlic", slug: "garlic", category: "Flavor & Fats", emoji: "🧄",
    description: "Flavor foundation of cuisines worldwide. Cooked garlic is mellow and sweet — raw is too harsh for babies.",
    introAgeText: "6 months (cooked)", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Allicin (immune-supporting), vitamin C, B6, manganese",
    benefits: "Prebiotic compounds feed good gut bacteria. Early flavor variety (garlic, spices, herbs) predicts less picky eating.",
    howToChoose: "Firm, heavy heads with tight skin. Avoid sprouting (bitter) or soft cloves. Pre-peeled is fine.",
    serve69: "Sauté minced garlic as a base for veggies, lentils, and meats — it melts into food. Roast whole heads until caramel-sweet; squeeze cloves into mash.",
    serve912: "Garlic bread soldiers, roasted garlic in hummus and sauces, garlic butter pasta.",
    serve12Plus: "Cook all family meals with garlic as usual. Garlic confit on toast, aioli-style dips (pasteurized egg).",
    storage: "Counter in ventilated spot 3–5 weeks. Never store raw garlic in oil at room temp (botulism risk).",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Cinnamon", slug: "cinnamon", category: "Flavor & Fats", emoji: "🫚",
    description: "Warm, sweet spice that makes oatmeal and fruit irresistible. Choose Ceylon (true cinnamon) for regular use.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Antioxidants, manganese",
    benefits: "Adds sweetness perception without sugar. Pairs with iron-rich oats and fruits. Early spice exposure builds flavor acceptance.",
    howToChoose: "Ceylon ('true') cinnamon for daily use — cassia has high coumarin which shouldn't be over-consumed. Small amounts of either are fine.",
    serve69: "Dust lightly on oatmeal, sweet potato, banana, and yogurt. Simmer a stick in cooking water (remove before serving). Start with a pinch.",
    serve912: "Cinnamon toast, baked apples and pears, French toast, muffins, roasted squash with cinnamon.",
    serve12Plus: "Snickerdoodle-style treats (low sugar), horchata oatmeal, cinnamon sugar pita chips (light sugar).",
    storage: "Ground cinnamon keeps 6–12 months sealed in a dark place. Sticks keep 2–3 years.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Olive Oil", slug: "olive-oil", category: "Flavor & Fats", emoji: "🫒",
    description: "Liquid gold for baby brains. Drizzle on everything — babies need far more fat per pound than adults.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Monounsaturated fats, vitamin E, polyphenols",
    benefits: "Healthy fats are 30–40% of a baby's calories needs. Helps absorb vitamins A, D, E, K from veggies. Anti-inflammatory polyphenols.",
    howToChoose: "Extra-virgin in a dark bottle. Peppery bite = fresh polyphenols. Fine for cooking despite myths (stable up to ~400°F).",
    serve69: "Drizzle generously over veggies, grains, and proteins. Stir into mashed foods. Use for roasting and sautéing baby meals. ~1–2 tsp per meal is great.",
    serve912: "Dipping oil (mild) for bread, pesto base, salad dressings, roasting everything.",
    serve12Plus: "Family cooking staple. Olive oil cakes, focaccia dipping, finishing oil on soups.",
    storage: "Cool dark pantry; use within 6–8 weeks of opening for best nutrition. Never refrigerate (clouds but harmless).",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Butter", slug: "butter", category: "Flavor & Fats", emoji: "🧈",
    description: "Rich, satisfying dairy fat. Contains milk allergen — but most milk-allergic kids tolerate baked milk (ask your allergist).",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Dairy", containsAllergens: "Cow's milk",
    chokingRisk: "Low",
    nutrition: "Vitamin A, healthy fats, butyrate",
    benefits: "Butyrate supports gut lining health. Makes vegetables delicious (a serious nutritional strategy!). Fat-soluble vitamin delivery vehicle.",
    howToChoose: "Unsalted for babies (sodium control). Grass-fed has more vitamin K2 and omega-3s. Ghee is nearly casein-free (still confirm with allergist if allergic).",
    serve69: "Melt into veggies, grains, and eggs. Thin spread on toast. Use for sautéing. Small amounts — olive oil should still be the main added fat.",
    serve912: "Garlic butter pasta, buttered toast soldiers for dipping, baking, popcorn topping (popcorn itself only at 4+).",
    serve12Plus: "Normal family use in cooking and baking. Compound butters with herbs, honey butter after 12 months.",
    storage: "Refrigerate 1–3 months; freeze 6–9 months. Counter butter bell keeps 1 week (salted).",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Honey", slug: "honey", category: "Flavor & Fats", emoji: "🍯",
    description: "⚠️ NEVER before 12 months — honey can contain botulism spores that infants cannot fight. This includes baked goods.",
    introAgeText: "12 months+ ONLY", introAgeMonths: 12, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "High (botulism risk)",
    nutrition: "Natural sugars, trace antioxidants",
    benefits: "After 12 months: soothing for coughs (better than some medicines!) and a less-refined sweetener. Zero benefits justify the risk before one.",
    howToChoose: "After 12 months: raw or pasteurized both fine. Avoid honey sticks/jars baby could access. Check labels: honey hides in breads, crackers, cereals, and 'natural' cough syrups.",
    serve69: "DO NOT SERVE. No honey in any form: not raw, not baked, not in bread, not in tea, not on a pacifier. Infant botulism is life-threatening. Use fruit to sweeten instead.",
    serve912: "DO NOT SERVE. Same rule — wait until the first birthday even though baby seems ready for everything else. Double-check bread and cracker labels.",
    serve12Plus: "Safe from 12 months: drizzle on yogurt and toast, honey-mustard dips, baking, soothing warm drinks for coughs (with lemon). Still limit added sugars overall.",
    storage: "Pantry forever (crystallization is normal — warm gently). Keep out of reach of under-ones.",
    isIronRich: false, isProteinRich: false,
  },
];
