export interface SeedRecipe {
  title: string;
  slug: string;
  country?: string;
  cuisine?: string;
  isAdapted?: boolean;
  adaptedNote?: string;
  region: string;
  category: string;
  foodGroup: string;
  emoji: string;
  description: string;
  ageMinMonths: number;
  ageText: string;
  prepMinutes: number;
  spiceLevel: string;
  ingredients: string[];
  steps: string[];
  texture69: string;
  texture912: string;
  texture12Plus: string;
  allergens: string;
  nutritionBenefits: string;
  isFirstFood: boolean;
  baseFoodSlugs: string[];
  tips: string;
}

export const seedRecipes: SeedRecipe[] = [
  {
    title: "Soft Rice Kanji (Rice Porridge)",
    slug: "soft-rice-kanji",
    region: "Tamil Nadu",
    category: "Mains",
    foodGroup: "Grains",
    emoji: "🍚",
    description: "The classic Tamil first food — rice cooked until it collapses into a silky porridge. Gentle, filling, and endlessly customizable with dal, ghee, and veg.",
    ageMinMonths: 6, ageText: "6 months+", prepMinutes: 25, spiceLevel: "None",
    ingredients: ["1/4 cup rice (ponni or sona masoori)", "2 cups water", "1 tsp ghee (optional)", "Pinch of cumin powder (optional)"],
    steps: [
      "Rinse the rice well until the water runs mostly clear.",
      "Cook with 2 cups water until very soft and broken — pressure cooker 4–5 whistles or simmer 25 minutes in a pot.",
      "Mash thoroughly with the back of a spoon; add warm water to reach a smooth porridge consistency.",
      "Stir in ghee and cumin if using. No salt needed for babies under 12 months.",
      "Cool to lukewarm and always test the temperature before serving.",
    ],
    texture69: "Thin, smooth porridge that drips slowly off a spoon. Pre-load spoons and let baby self-feed.",
    texture912: "Thicker, mashable porridge with soft lumps. Mix in mashed dal or vegetables.",
    texture12Plus: "Soft mashed rice served with dal, sambar, rasam, or curd as part of family meals.",
    allergens: "Dairy (only if ghee is added)",
    nutritionBenefits: "Gentle first carbohydrates for energy. Ghee adds vitamin A and brain-building fats. Pair with dal for complete protein.",
    isFirstFood: true,
    baseFoodSlugs: ["rice", "ghee"],
    tips: "Start with 1–2 tablespoons once a day. Leftover kanji thickens — thin with warm water when reheating.",
  },
  {
    title: "Moong Dal Soup (Paruppu Thanni)",
    slug: "moong-dal-soup",
    region: "Tamil Nadu",
    category: "Mains",
    foodGroup: "Legumes",
    emoji: "🍲",
    description: "Golden, silky split-moong soup — the easiest lentil for tiny tummies to digest. A perfect iron-rich first food.",
    ageMinMonths: 6, ageText: "6 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["2 tbsp split yellow moong dal", "1.5 cups water", "Pinch of turmeric", "1/2 tsp ghee", "Pinch of cumin powder"],
    steps: [
      "Rinse the dal well and add to a pot or pressure cooker with water and turmeric.",
      "Pressure cook 3 whistles or simmer 20 minutes until the dal completely dissolves.",
      "Mash or blend smooth. For young babies, strain through a sieve for a silky soup.",
      "Warm the ghee, sizzle the cumin for 10 seconds, and stir into the soup.",
      "Serve lukewarm — thin enough to sip from a spoon, never watery-thin.",
    ],
    texture69: "Strained, silky soup or thin dal-water. Serve 2–3 tablespoons with a spoon.",
    texture912: "Thicker unstrained dal, mashed. Mix into rice for baby's first dal-rice.",
    texture12Plus: "Regular dal consistency with soft rice, rotis, or as a soup with a squeeze of lemon.",
    allergens: "Dairy (only if ghee is added)",
    nutritionBenefits: "Top plant iron and protein for babies, plus folate for growth. Turmeric adds gentle anti-inflammatory compounds.",
    isFirstFood: true,
    baseFoodSlugs: ["moong-dal", "ghee"],
    tips: "Moong dal causes the least gas of all lentils — ideal before introducing toor dal or chickpeas.",
  },
  {
    title: "Toor Dal Mash (Paruppu)",
    slug: "toor-dal-mash",
    region: "Tamil Nadu",
    category: "Mains",
    foodGroup: "Legumes",
    emoji: "🫘",
    description: "Creamy mashed pigeon-pea dal with ghee — the heart of Tamil dal-rice. Slightly heartier than moong dal.",
    ageMinMonths: 6, ageText: "6 months+", prepMinutes: 25, spiceLevel: "None",
    ingredients: ["1/4 cup toor dal (split pigeon peas)", "1 cup water", "Pinch of turmeric", "1 tsp ghee", "1 tbsp mashed soft rice (optional)"],
    steps: [
      "Rinse dal and pressure cook with water and turmeric for 4 whistles until very soft.",
      "Mash thoroughly while hot until creamy and smooth.",
      "Stir in ghee. Mix with mashed rice for classic paruppu sadam (dal-rice).",
      "Thin with warm water for younger babies; keep thicker as chewing improves.",
    ],
    texture69: "Smooth, creamy mash — thin with water to a soft puree consistency.",
    texture912: "Thick mashed dal-rice baby can scoop with hands or a spoon.",
    texture12Plus: "Dal-rice with ghee plus soft vegetable sides, like the family eats.",
    allergens: "Dairy (only if ghee is added)",
    nutritionBenefits: "Excellent protein, iron, folate, and B vitamins. Combining with rice creates complete protein.",
    isFirstFood: false,
    baseFoodSlugs: ["toor-dal", "ghee", "rice"],
    tips: "If baby finds toor dal gassy, start with moong dal soup for a week first, then transition.",
  },
  {
    title: "Ragi Porridge (Ragi Koozh)",
    slug: "ragi-porridge",
    region: "Karnataka",
    category: "Breakfast",
    foodGroup: "Millets",
    emoji: "🥣",
    description: "Karnataka and Tamil Nadu's beloved calcium-and-iron-rich millet porridge. Naturally sweet, earthy, and wonderful for weight gain.",
    ageMinMonths: 6, ageText: "6 months+", prepMinutes: 15, spiceLevel: "None",
    ingredients: ["2 tbsp ragi (finger millet) flour", "1 cup water", "1/4 cup breastmilk, formula, or coconut milk", "2 tbsp mashed banana or mango for sweetness"],
    steps: [
      "Whisk ragi flour into cold water until completely smooth — no lumps.",
      "Cook on medium heat, stirring continuously for 5–7 minutes until glossy, thick, and aromatic.",
      "Cool slightly, then thin with milk and top with mashed fruit. Never use cow's milk as the base under 12 months.",
      "Serve warm. Porridge thickens as it sits — stir in warm water if needed.",
    ],
    texture69: "Smooth, pourable porridge. Strain if any lumps remain.",
    texture912: "Thicker porridge baby can scoop; add soft fruit chunks for texture.",
    texture12Plus: "Thick ragi malt in a cup, ragi dosa, or soft ragi balls (mudde) with sambar.",
    allergens: "Dairy (only if cow's milk is used — avoid as main milk under 12 months)",
    nutritionBenefits: "One of the best plant sources of calcium plus iron and fiber. Great for bones, weight gain, and digestion.",
    isFirstFood: true,
    baseFoodSlugs: ["ragi", "banana", "coconut"],
    tips: "Sprouted ragi flour (ragi malt) is even more nutritious and easier to digest — look for it in Indian stores.",
  },
  {
    title: "Vegetable Khichdi",
    slug: "vegetable-khichdi",
    region: "Pan-Indian",
    category: "Mains",
    foodGroup: "Grains",
    emoji: "🍛",
    description: "India's ultimate one-pot baby meal — rice and moong dal cooked with soft vegetables into a comforting, complete mush.",
    ageMinMonths: 6, ageText: "6 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["2 tbsp rice", "1 tbsp split moong dal", "2 tbsp mixed veg (carrot, beans, pumpkin)", "1.5 cups water", "Pinch of turmeric", "1 tsp ghee"],
    steps: [
      "Rinse rice and dal together; chop vegetables very small.",
      "Add everything except ghee to a pressure cooker with water.",
      "Cook 4 whistles (or simmer 30 minutes) until everything is falling-apart soft.",
      "Mash well, stir in ghee, and cool to lukewarm before serving.",
    ],
    texture69: "Well-mashed, soft khichdi — blend briefly if baby is just starting out.",
    texture912: "Lightly mashed with visible soft veggie pieces for chewing practice.",
    texture12Plus: "Regular khichdi with curd, plus ghee-roasted papad pieces for crunch (supervised).",
    allergens: "Dairy (only if ghee is added)",
    nutritionBenefits: "Complete protein from rice + dal, vitamin A from vegetables, and iron — a genuinely complete baby meal in one pot.",
    isFirstFood: true,
    baseFoodSlugs: ["rice", "moong-dal", "carrot", "green-beans", "butternut-squash", "ghee"],
    tips: "Rotate the vegetables weekly (peas, spinach, bottle gourd) — each one counts toward food variety!",
  },
  {
    title: "Soft Plain Idli",
    slug: "soft-plain-idli",
    region: "Tamil Nadu",
    category: "Breakfast",
    foodGroup: "Grains",
    emoji: "🫓",
    description: "Cloud-soft steamed rice cakes — fermented, probiotic, and practically designed for baby fists. A South Indian superpower food.",
    ageMinMonths: 6, ageText: "6 months+", prepMinutes: 15, spiceLevel: "None",
    ingredients: ["Fresh idli batter (homemade or store-bought without preservatives)", "Water for steaming", "Ghee or mashed dal for serving"],
    steps: [
      "Bring steamer water to a rolling boil. Lightly grease idli moulds.",
      "Pour batter 3/4 full — don't overfill or idlis turn dense.",
      "Steam 10–12 minutes until a toothpick comes out clean.",
      "Rest 2 minutes, scoop out with a wet spoon, and cool to lukewarm.",
      "Mash with ghee, dal, sambar, or curd before serving to babies.",
    ],
    texture69: "Mash idli completely with dal, sambar, or curd into a soft scoopable meal.",
    texture912: "Crumble into small soft pieces baby can pick up; serve with dal for dipping.",
    texture12Plus: "Mini idlis (button idlis) for dipping in sambar and chutney — great party food!",
    allergens: "None common (fermented rice + urad dal); serving sides may add Dairy/Coconut",
    nutritionBenefits: "Fermentation creates probiotics and B vitamins while making the meal extra easy to digest. Low-fat, soft, and filling.",
    isFirstFood: false,
    baseFoodSlugs: ["rice"],
    tips: "Day-old idlis make the best idli upma. Freeze steamed idlis and re-steam for 3 minutes — good as fresh.",
  },
  {
    title: "Ven Pongal (Rice & Moong Dal)",
    slug: "ven-pongal",
    region: "Tamil Nadu",
    category: "Breakfast",
    foodGroup: "Grains",
    emoji: "🍚",
    description: "Creamy, ghee-kissed rice and moong dal mash with a whisper of cumin and pepper. Tamil comfort in a bowl.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 30, spiceLevel: "Very mild",
    ingredients: ["2 tbsp rice", "1 tbsp split moong dal", "1.5 cups water", "1 tsp ghee", "Tiny pinch each of cumin and crushed black pepper"],
    steps: [
      "Dry-roast the moong dal 2 minutes until fragrant (optional but traditional).",
      "Cook rice + dal with water until very soft and creamy — 4 whistles or 30 minutes simmered.",
      "Mash well. Warm ghee, sizzle cumin and pepper 10 seconds, and stir through.",
      "Serve warm with a spoon of curd on the side for older babies.",
    ],
    texture69: "Creamy, well-mashed pongal — thin with warm water if needed.",
    texture912: "Soft scoopable pongal; let baby practice with a spoon.",
    texture12Plus: "Regular pongal with coconut chutney and sambar, like the family breakfast.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Complete protein, gentle fiber, and sustained energy. Black pepper in tiny amounts aids digestion.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "moong-dal", "ghee"],
    tips: "Keep pepper truly minimal for babies — you should barely taste it. Increase gradually after 12 months.",
  },
  {
    title: "Plain Soft Dosa",
    slug: "plain-soft-dosa",
    region: "Tamil Nadu",
    category: "Breakfast",
    foodGroup: "Grains",
    emoji: "🥞",
    description: "Pliable, soft (not crispy!) mini dosas that babies can tear, dip, and gnaw. Fermented goodness in finger-food form.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["Fresh dosa batter", "1 tsp ghee or oil", "Mild coconut chutney or dal for serving (no salt for baby's portion)"],
    steps: [
      "Heat a tawa on medium. Pour a small ladle of batter and spread into a mini dosa.",
      "Drizzle ghee around the edges. Cook until set but still SOFT and pliable — do not brown or crisp it.",
      "Fold and cool slightly. Cut into adult-finger-sized strips.",
      "Serve with mashed dal or fresh mild coconut chutney for dipping.",
    ],
    texture69: "Tear into soft strips; soak briefly in dal so pieces are extra soft and easy to gum.",
    texture912: "Soft strips for dipping in sambar, dal, or curd.",
    texture12Plus: "Regular dosas with chutney and sambar; let your toddler practice tearing pieces.",
    allergens: "Coconut (if chutney served); Dairy (if ghee used)",
    nutritionBenefits: "Fermented batter is rich in B vitamins and probiotics. A fun vehicle for protein-rich dals and iron-rich sambar.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "coconut", "ghee"],
    tips: "Baby dosas should be white and soft — save the golden crispy ones for adults. Crispy edges can scratch little mouths.",
  },
  {
    title: "Curd Rice (Thayir Sadam)",
    slug: "curd-rice",
    region: "Tamil Nadu",
    category: "Mains",
    foodGroup: "Dairy",
    emoji: "🍚",
    description: "Cooling mashed rice folded through creamy curd with a gentle cumin-ghee tadka. Comforting, probiotic, and perfect for hot days.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 15, spiceLevel: "None",
    ingredients: ["1/4 cup overcooked soft rice", "1/4 cup plain whole-milk curd (yogurt)", "1 tbsp milk", "1/2 tsp ghee", "Pinch of cumin + tiny pinch of hing (asafoetida)"],
    steps: [
      "Mash the warm rice completely smooth with the back of a spoon.",
      "Whisk curd with milk until creamy, then fold through the rice.",
      "Warm ghee, sizzle cumin and hing 10 seconds, and stir through the rice.",
      "Serve fresh at room temperature within 2 hours. No salt for babies.",
    ],
    texture69: "Completely smooth and creamy — thin with milk to a soft porridge.",
    texture912: "Creamy with tiny soft rice lumps; add mashed banana or soft pomegranate seeds (supervised).",
    texture12Plus: "Classic thayir sadam with pomegranate, grated carrot, and coriander — a lunchbox hero.",
    allergens: "Dairy",
    nutritionBenefits: "Probiotics for gut health, calcium for bones, and complete protein. Wonderfully cooling and easy when baby is teething.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "yogurt", "ghee"],
    tips: "Always use fresh, string-free curd. Discard leftovers after 2 hours at room temperature — curd spoils fast.",
  },
  {
    title: "Carrot-Beans Poriyal",
    slug: "carrot-beans-poriyal",
    region: "Tamil Nadu",
    category: "Sides",
    foodGroup: "Vegetables",
    emoji: "🥕",
    description: "Tamil-style dry vegetable sauté — here steamed extra-soft and tossed with coconut. Sweet, colorful, and endlessly variable.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["1 carrot + 4 green beans, chopped very small", "1 tsp coconut oil or any oil", "Pinch of turmeric", "1 tbsp freshly grated coconut", "1 curry leaf (remove before serving)"],
    steps: [
      "Steam the chopped vegetables until completely soft and smashable — about 12–15 minutes.",
      "Warm oil with turmeric and curry leaf for 30 seconds.",
      "Toss the soft vegetables through for 1 minute. Remove the curry leaf.",
      "Mix in grated coconut and serve warm with rice and dal.",
    ],
    texture69: "Mash the steamed vegetables coarsely with rice and dal.",
    texture912: "Tiny soft pieces mixed into rice — great for pincer-grasp practice.",
    texture12Plus: "Regular poriyal as a side dish; try cabbage, beetroot, and cluster-beans versions.",
    allergens: "Coconut",
    nutritionBenefits: "Beta-carotene for eyes and immunity plus fiber. Coconut adds brain-healthy fats that help absorb vitamin A.",
    isFirstFood: false,
    baseFoodSlugs: ["carrot", "green-beans", "coconut"],
    tips: "Swap vegetables freely — beetroot poriyal turns everything gloriously pink and babies love it.",
  },
  {
    title: "Pumpkin Erissery",
    slug: "pumpkin-erissery",
    region: "Kerala",
    category: "Sides",
    foodGroup: "Vegetables",
    emoji: "🎃",
    description: "Kerala's silky pumpkin-and-coconut mash — naturally sweet, gorgeously orange, and soft enough to gum.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["1/2 cup pumpkin cubes", "1 tbsp coconut ground with 1/4 tsp cumin", "Pinch of turmeric", "1/2 cup water", "1/2 tsp coconut oil"],
    steps: [
      "Simmer pumpkin with turmeric and water until completely tender, about 12 minutes.",
      "Stir in the coconut-cumin paste and simmer 3 more minutes.",
      "Mash lightly — keep it rustic, not pureed.",
      "Drizzle coconut oil and serve warm with rice.",
    ],
    texture69: "Mash smooth and thin slightly with warm water.",
    texture912: "Lightly mashed with soft chunks for chewing practice.",
    texture12Plus: "Serve as a side with rice, sambar, and a papad — full Kerala meals vibes.",
    allergens: "Coconut",
    nutritionBenefits: "Superb vitamin A for vision and immunity, plus hydrating fiber. Coconut fat boosts absorption of fat-soluble vitamins.",
    isFirstFood: false,
    baseFoodSlugs: ["butternut-squash", "coconut"],
    tips: "Any sweet pumpkin or butternut squash works. Red (lal bhopla) pumpkin is sweetest.",
  },
  {
    title: "Soft Egg Bhurji",
    slug: "soft-egg-bhurji",
    region: "Pan-Indian",
    category: "Sides",
    foodGroup: "Eggs",
    emoji: "🍳",
    description: "Pillowy soft-scrambled egg with turmeric and sweet tomato — a gentle way to serve the egg allergen regularly.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 10, spiceLevel: "None",
    ingredients: ["1 egg", "1 tbsp milk", "1 tsp butter or ghee", "Pinch of turmeric", "1 tbsp peeled, finely minced tomato"],
    steps: [
      "Whisk egg with milk and turmeric until completely uniform.",
      "Melt butter on low heat and add the tomato; soften 1 minute.",
      "Pour in egg and stir slowly into large soft curds. Cook until just set with NO runny parts.",
      "Cool slightly and cut or crumble into baby-safe pieces.",
    ],
    texture69: "Mash the soft scramble finely and mix with a little mashed potato or rice.",
    texture912: "Small soft curds baby can pick up; stuff into soft dosa rolls.",
    texture12Plus: "Egg bhurji toast soldiers, bhurji chapati rolls, or mixed into fried rice.",
    allergens: "Egg, Dairy",
    nutritionBenefits: "Choline for brain development, plus iron, B12, and vitamin D. One of the most nutritious foods per bite.",
    isFirstFood: false,
    baseFoodSlugs: ["egg", "butter", "tomato"],
    tips: "Introduce egg in the morning the first time and watch for 2 hours. Then serve egg 2–3 times weekly.",
  },
  {
    title: "Mild Baby Sambar",
    slug: "mild-baby-sambar",
    region: "Tamil Nadu",
    category: "Mains",
    foodGroup: "Legumes",
    emoji: "🍲",
    description: "Everything you love about sambar — dal, vegetables, gentle spice — rebalanced for babies: no chili, minimal tamarind, extra soft.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 30, spiceLevel: "Very mild",
    ingredients: ["2 tbsp toor dal", "Mixed veg: carrot, beans, pumpkin (chopped small)", "1 small tomato", "1/2 tsp homemade mild sambar powder (no chili) or turmeric + coriander", "Pea-sized tamarind soaked in water (optional)", "1 tsp ghee + pinch of cumin for tadka"],
    steps: [
      "Pressure cook dal with vegetables, tomato, and turmeric until everything is very soft.",
      "Stir in the mild spice and strained tamarind water; simmer 5 minutes.",
      "Mash lightly so vegetables break down but the dal stays hearty.",
      "Temper cumin in ghee and stir through. Serve with soft rice or idli.",
    ],
    texture69: "Not recommended under 8 months — the flavors are complex. From 8 months, mash well with rice.",
    texture912: "Lightly mashed sambar-rice; vegetables should still be smashable between fingers.",
    texture12Plus: "Family sambar (still mild on chili) with rice, idli, dosa, or pongal.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Iron from dal, vitamin A and C from vegetables, and tomato's vitamin C triples the dal's iron absorption.",
    isFirstFood: false,
    baseFoodSlugs: ["toor-dal", "carrot", "green-beans", "tomato", "ghee"],
    tips: "Make sambar powder baby-safe at home: roast and grind coriander seeds, cumin, toor dal, and a little coconut — no chilies.",
  },
  {
    title: "Baby Tomato Rasam",
    slug: "baby-tomato-rasam",
    region: "Tamil Nadu",
    category: "Mains",
    foodGroup: "Vegetables",
    emoji: "🍅",
    description: "Thin, soul-warming tomato-pepper broth with garlic — Tamil comfort for sniffles, served over rice with ghee.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 20, spiceLevel: "Very mild",
    ingredients: ["1 ripe tomato, chopped", "1 tbsp cooked toor dal mashed in 1 cup water", "1 small garlic clove, crushed", "Pinch each of turmeric, cumin, and crushed black pepper", "1/2 tsp ghee"],
    steps: [
      "Boil tomato with dal-water, turmeric, cumin, and pepper for 5–7 minutes until the tomato melts.",
      "In ghee, sizzle the garlic and a pinch more cumin 30 seconds; pour into the rasam.",
      "Simmer 2 minutes. For young babies, strain out tomato skins.",
      "Serve as a thin soup or poured over mashed rice with ghee.",
    ],
    texture69: "Not for under 8 months. From 8 months, serve strained and thin over mashed rice.",
    texture912: "Unstrained thin rasam-rice; let baby sip from a cup too.",
    texture12Plus: "Rasam-rice with ghee and roasted appalam (supervised), plus a full family meal.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Hydrating and rich in vitamin C and lycopene. Garlic and pepper traditionally soothe colds and aid digestion.",
    isFirstFood: false,
    baseFoodSlugs: ["tomato", "toor-dal", "garlic", "ghee"],
    tips: "Rasam is magic during colds — warm, hydrating, and easy to swallow when appetite is low.",
  },
  {
    title: "Vegetable Kootu",
    slug: "vegetable-kootu",
    region: "Tamil Nadu",
    category: "Mains",
    foodGroup: "Vegetables",
    emoji: "🥬",
    description: "Hearty Tamil stew of vegetables simmered with moong dal and coconut — mild, creamy, and filling.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 25, spiceLevel: "None",
    ingredients: ["1/2 cup chopped veg (bottle gourd or chow chow + carrot)", "2 tbsp split moong dal", "1 tbsp coconut ground with 1/4 tsp cumin", "Pinch of turmeric", "1 tsp oil or ghee"],
    steps: [
      "Cook dal and vegetables together with turmeric and water until very soft.",
      "Stir in the coconut-cumin paste and simmer 5 minutes.",
      "Mash lightly and finish with oil or ghee.",
      "Serve with rice — kootu doubles as both dal and vegetable side.",
    ],
    texture69: "From 8 months: mash well into a thick, scoopable stew.",
    texture912: "Lightly mashed with soft vegetable pieces.",
    texture12Plus: "Family-style kootu with rice and rasam — the classic Tamil combo meal.",
    allergens: "Coconut; Dairy (if ghee used)",
    nutritionBenefits: "Protein from dal, fiber and vitamins from vegetables, and healthy fats from coconut — a balanced one-pot meal.",
    isFirstFood: false,
    baseFoodSlugs: ["moong-dal", "carrot", "zucchini", "coconut", "ghee"],
    tips: "Chow chow (chayote) and bottle gourd practically melt when cooked — perfect kootu vegetables for babies.",
  },
  {
    title: "Mild Baby Chicken Curry",
    slug: "mild-baby-chicken-curry",
    region: "Kerala",
    category: "Mains",
    foodGroup: "Meat",
    emoji: "🍗",
    description: "Tender chicken simmered in a gentle coconut-tomato gravy — all the flavor of Kerala curry with none of the heat.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 35, spiceLevel: "Very mild",
    ingredients: ["100g boneless chicken thigh pieces", "2 tbsp finely minced onion", "1 small tomato, chopped", "1/2 tsp ginger-garlic paste", "1/4 tsp each turmeric and coriander powder", "1/2 cup thin coconut milk", "1 curry leaf (remove before serving)"],
    steps: [
      "Sauté onion and ginger-garlic paste in oil until soft and sweet, about 5 minutes.",
      "Add tomato and ground spices; cook until the tomato melts.",
      "Add chicken and 1/2 cup water; simmer 15–20 minutes until the chicken shreds easily.",
      "Stir in coconut milk and warm through. Remove curry leaf.",
      "Shred or mince the chicken very finely and mix back into the gravy with rice.",
    ],
    texture69: "From 8 months: finely minced chicken in plenty of gravy, mixed with mashed rice.",
    texture912: "Small shreds in gravy over soft rice; chicken should fall apart at a touch.",
    texture12Plus: "Bite-size pieces with rice, appam, or soft chapati; mild heat can increase slowly.",
    allergens: "Coconut",
    nutritionBenefits: "Superb heme iron and zinc that absorb far better than plant iron, plus high-quality protein for growth.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "tomato", "garlic", "coconut"],
    tips: "Thigh meat stays juicy — breast dries out and gets chalky for babies. Always cook chicken to steaming shreddable.",
  },
  {
    title: "Paneer Mash",
    slug: "paneer-mash",
    region: "North Indian",
    category: "Sides",
    foodGroup: "Dairy",
    emoji: "🧀",
    description: "Cloud-soft crumbled paneer warmed with milk and gentle spices — a calcium-rich vegetarian protein for babies.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 10, spiceLevel: "None",
    ingredients: ["50g fresh soft paneer (malai paneer)", "1 tbsp milk or water", "Pinch of turmeric and cumin", "1 tsp ghee"],
    steps: [
      "Crumble the paneer finely with your fingers.",
      "Warm with milk, turmeric, and cumin for 2–3 minutes until soft and creamy.",
      "Mash smooth and stir in ghee.",
      "Serve with mashed rice, khichdi, or soft roti pieces.",
    ],
    texture69: "From 8 months: smooth creamy mash, thinned with milk if needed.",
    texture912: "Soft crumbles baby can pick up; mix into rice or stuff into dosa.",
    texture12Plus: "Small soft cubes in curries, bhurji, sandwiches, and wraps.",
    allergens: "Dairy",
    nutritionBenefits: "Concentrated calcium and protein for growing bones and muscles. Fresh paneer is lower in sodium than aged cheese.",
    isFirstFood: false,
    baseFoodSlugs: ["paneer", "ghee"],
    tips: "Use the freshest, softest paneer you can find — firm rubbery paneer is hard for babies to manage.",
  },
  {
    title: "Foxtail Millet Khichdi",
    slug: "foxtail-millet-khichdi",
    region: "Andhra Pradesh",
    category: "Mains",
    foodGroup: "Millets",
    emoji: "🌾",
    description: "Nutty foxtail millet (korra/thinai) cooked khichdi-style with moong dal and vegetables — ancient grain, modern superfood.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["2 tbsp foxtail millet", "1 tbsp split moong dal", "2 tbsp mixed veg (carrot, beans)", "1.5 cups water", "Pinch of turmeric", "1 tsp ghee"],
    steps: [
      "Rinse millet very well — millets need thorough washing.",
      "Combine everything except ghee with water (millets need a 1:4 grain-to-water ratio).",
      "Pressure cook 4–5 whistles or simmer 25–30 minutes until very soft.",
      "Mash well, stir in ghee, and rest 5 minutes (millets continue softening).",
    ],
    texture69: "From 8 months: well-mashed and moist — millets dry out, so keep it loose with water.",
    texture912: "Soft scoopable khichdi with mashable veggie pieces.",
    texture12Plus: "Fluffy millet khichdi or upma with coconut chutney and curd.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Rich in iron, B vitamins, and fiber with a low glycemic index — keeps little tummies full longer than rice.",
    isFirstFood: false,
    baseFoodSlugs: ["moong-dal", "carrot", "green-beans", "ghee"],
    tips: "Rotate millets across the week (foxtail, little millet, kodo) — each has a slightly different nutrient profile.",
  },
  {
    title: "Keerai Masiyal (Greens Mash)",
    slug: "keerai-masiyal",
    region: "Tamil Nadu",
    category: "Sides",
    foodGroup: "Vegetables",
    emoji: "🥬",
    description: "Tamil-style mashed greens with dal and garlic — an iron powerhouse disguised as comfort food.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["1 cup chopped spinach or arai keerai", "1 tbsp split moong dal", "1 small tomato, chopped", "1 small garlic clove", "Pinch of cumin", "1 tsp ghee"],
    steps: [
      "Cook greens with dal, tomato, and 1/2 cup water until completely wilted and soft.",
      "Mash thoroughly — greens should be silky, not stringy.",
      "Temper crushed garlic and cumin in ghee until golden; stir through the mash.",
      "Serve with rice and ghee. A squeeze of lemon (for 12m+) boosts iron absorption further.",
    ],
    texture69: "From 8 months: silky smooth mash — blend briefly if any stringy bits remain.",
    texture912: "Rustic mash with rice; the garlic tadka makes it irresistible.",
    texture12Plus: "Classic keerai masiyal with rice, rasam, and appalam.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Iron, folate, and vitamin K from greens; tomato's vitamin C multiplies iron absorption. One of the best veg iron meals.",
    isFirstFood: false,
    baseFoodSlugs: ["spinach", "moong-dal", "tomato", "garlic", "ghee"],
    tips: "Arai keerai (spleen amaranth) and murungai keerai (moringa leaves) are traditional Tamil choices — moringa is extraordinarily nutritious.",
  },
  {
    title: "Mango Yogurt (Lassi-Style)",
    slug: "mango-yogurt",
    region: "Pan-Indian",
    category: "Snacks & Drinks",
    foodGroup: "Dairy",
    emoji: "🥭",
    description: "Two-ingredient sunshine — ripe mango blended with creamy curd and cardamom. No added sugar needed, ever.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 5, spiceLevel: "None",
    ingredients: ["1/2 very ripe mango (alphonso or kesar)", "1/4 cup plain whole-milk curd", "2 tbsp water or milk", "Tiny pinch of cardamom"],
    steps: [
      "Scoop the mango flesh, checking carefully for any fibrous bits.",
      "Blend with curd, water, and cardamom until completely smooth.",
      "Serve immediately in an open cup or with a spoon — fresh is best.",
    ],
    texture69: "From 8 months: smooth and drinkable; spoon-feed or offer in an open cup.",
    texture912: "Thicker smoothie-bowl consistency topped with soft mango cubes.",
    texture12Plus: "Mango lassi in a cup with a straw, or frozen into popsicles.",
    allergens: "Dairy",
    nutritionBenefits: "Vitamin A and C from mango plus probiotics, calcium, and protein from curd — dessert that's genuinely nutritious.",
    isFirstFood: false,
    baseFoodSlugs: ["mango", "yogurt"],
    tips: "Only make with fully ripe, sweet mangoes — sour mango + curd is a flavor babies (and adults) reject.",
  },
  {
    title: "Pesarattu (Moong Dal Dosa)",
    slug: "pesarattu",
    region: "Andhra Pradesh",
    category: "Breakfast",
    foodGroup: "Legumes",
    emoji: "🥞",
    description: "Andhra's protein-packed green moong dosa with ginger — crisp for adults, made soft and small for babies.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 25, spiceLevel: "Very mild",
    ingredients: ["1/4 cup whole green moong, soaked 4 hours", "Small piece of ginger", "1/4 tsp cumin", "Water as needed", "Ghee for cooking", "Curd for serving"],
    steps: [
      "Grind soaked moong with ginger, cumin, and water into a smooth dosa-like batter. Rest 15 minutes.",
      "Spread small thin dosas on a medium-hot tawa with ghee.",
      "Cook until set but still soft and green — do not crisp for babies.",
      "Cut into strips and serve with plain curd for dipping.",
    ],
    texture69: "Wait until 9 months — whole moong is heartier. Then serve soft strips soaked briefly in curd.",
    texture912: "Soft strips with curd; tear into smaller pieces as pincer grasp develops.",
    texture12Plus: "Regular pesarattu with ginger chutney and upma — the classic Andhra combo.",
    allergens: "Dairy (if served with curd/ghee)",
    nutritionBenefits: "Whole moong brings extra fiber, iron, and protein versus split dal. Ginger aids digestion.",
    isFirstFood: false,
    baseFoodSlugs: ["moong-dal", "yogurt", "ghee"],
    tips: "No fermentation needed — pesarattu batter is instant once the moong is soaked. Great for busy mornings.",
  },
  {
    title: "Ragi Dosa",
    slug: "ragi-dosa",
    region: "Karnataka",
    category: "Breakfast",
    foodGroup: "Millets",
    emoji: "🥞",
    description: "Earthy, calcium-rich millet dosas — lacy for adults, soft and small for babies, with dal for dipping.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["2 tbsp ragi flour", "1 tbsp rice flour", "Water to make a thin batter", "Pinch of cumin", "Ghee for cooking"],
    steps: [
      "Whisk flours with water into a thin, pourable batter with cumin. Rest 10 minutes.",
      "Pour small ladles onto a medium tawa — the batter spreads itself lacy.",
      "Cook with ghee until set but soft and pliable. Fold while soft.",
      "Serve warm with moong dal or sambar for dipping.",
    ],
    texture69: "Wait until 9 months. Then tear soft dosa into small pieces and soak in dal.",
    texture912: "Soft torn pieces for dipping; the earthy flavor pairs beautifully with coconut.",
    texture12Plus: "Crisp-edged ragi dosas with chutney and sambar like the family eats.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Calcium and iron from ragi in a fun finger-food format. Combining with dal completes the protein.",
    isFirstFood: false,
    baseFoodSlugs: ["ragi", "rice", "ghee"],
    tips: "Ragi batter has no gluten so it won't stretch — pour, don't spread. Small dosas flip easiest.",
  },
  {
    title: "Idli Upma",
    slug: "idli-upma",
    region: "Tamil Nadu",
    category: "Breakfast",
    foodGroup: "Grains",
    emoji: "🍚",
    description: "Crumbled leftover idlis tossed with turmeric, carrot, and a gentle tadka — the tastiest way to use day-old idlis.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 15, spiceLevel: "Very mild",
    ingredients: ["2 leftover idlis, crumbled", "1 tsp oil", "Pinch each of turmeric and cumin", "2 tbsp finely grated carrot", "1 tbsp chopped coriander leaves"],
    steps: [
      "Warm oil and sizzle cumin and turmeric 10 seconds.",
      "Add grated carrot with a sprinkle of water; soften 2 minutes.",
      "Toss in crumbled idli and stir gently 2 minutes until warmed through and lightly golden.",
      "Finish with coriander. Keep it soft and moist — sprinkle water if it looks dry.",
    ],
    texture69: "Wait until 9 months. Then serve soft and moist — dry crumbles are hard to swallow.",
    texture912: "Soft crumbles baby can scoop; add a spoon of curd to bind.",
    texture12Plus: "Classic idli upma with coconut chutney on the side.",
    allergens: "None common",
    nutritionBenefits: "Fermented grains plus vitamin A from carrot. A zero-waste breakfast that repurposes leftovers brilliantly.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "carrot"],
    tips: "Fresh idlis turn mushy in upma — day-old refrigerated idlis crumble perfectly. Plan ahead!",
  },
  {
    title: "Coconut Avial",
    slug: "coconut-avial",
    region: "Kerala",
    category: "Sides",
    foodGroup: "Vegetables",
    emoji: "🥥",
    description: "Kerala's famous mixed-vegetable coconut medley — colorful, creamy, and naturally sweet from the vegetables.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["1 cup mixed veg sticks (carrot, beans, pumpkin, raw banana)", "2 tbsp coconut ground with 1/4 tsp cumin", "1 tbsp plain curd", "1/2 tsp coconut oil", "1 curry leaf (remove before serving)"],
    steps: [
      "Cook the vegetable sticks with turmeric and 1/2 cup water until completely soft.",
      "Fold in the coconut paste and warm through 3 minutes — don't boil hard.",
      "Off the heat, stir in curd and coconut oil. Remove curry leaf.",
      "Mash lightly for babies; serve with rice.",
    ],
    texture69: "Wait until 9 months. Then mash the soft vegetables coarsely with rice.",
    texture912: "Soft vegetable pieces in creamy coconut coating — wonderful texture exposure.",
    texture12Plus: "Full avial as a sadhya-style side with rice and sambar.",
    allergens: "Coconut, Dairy (curd)",
    nutritionBenefits: "Four-plus vegetables in one dish means broad vitamins and fiber; coconut and curd add healthy fats and probiotics.",
    isFirstFood: false,
    baseFoodSlugs: ["carrot", "green-beans", "butternut-squash", "banana", "coconut", "yogurt"],
    tips: "Raw (green) banana must be cooked very soft — undercooked pieces are chalky. When in doubt, cook longer.",
  },
  {
    title: "Baby Egg Curry",
    slug: "baby-egg-curry",
    region: "Kerala",
    category: "Mains",
    foodGroup: "Eggs",
    emoji: "🍳",
    description: "Boiled eggs simmered in a mild coconut-tomato gravy — Kerala-style comfort that keeps egg in weekly rotation.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 25, spiceLevel: "Very mild",
    ingredients: ["2 eggs, hard-boiled and halved", "2 tbsp minced onion", "1 small tomato, chopped", "1/2 tsp ginger-garlic paste", "1/4 tsp each turmeric and coriander", "1/2 cup thin coconut milk"],
    steps: [
      "Soften onion and ginger-garlic in oil 5 minutes until sweet.",
      "Add tomato and spices; cook until melted into a masala.",
      "Pour in coconut milk and 1/4 cup water; simmer 3 minutes.",
      "Add halved eggs and simmer gently 5 minutes so they absorb flavor.",
      "For babies, mash the egg into the gravy and serve over rice.",
    ],
    texture69: "Wait until 9 months. Then mash egg completely into gravy with rice.",
    texture912: "Finely chopped egg in gravy over soft rice.",
    texture12Plus: "Halved eggs in curry with rice, appam, or chapati.",
    allergens: "Egg, Coconut",
    nutritionBenefits: "Choline, iron, and B12 from egg plus hydrating coconut. An easy way to keep the egg allergen in regular rotation.",
    isFirstFood: false,
    baseFoodSlugs: ["egg", "tomato", "garlic", "coconut"],
    tips: "Already-peeled boiled eggs in the fridge = 15-minute egg curry on busy nights.",
  },
  {
    title: "Bajra Khichdi",
    slug: "bajra-khichdi",
    region: "Rajasthan",
    category: "Mains",
    foodGroup: "Millets",
    emoji: "🌾",
    description: "Warming pearl-millet khichdi with pumpkin and ghee — Rajasthani winter comfort, rich in iron and magnesium.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 40, spiceLevel: "None",
    ingredients: ["2 tbsp bajra (pearl millet), soaked 2 hours", "1 tbsp split moong dal", "2 tbsp pumpkin + carrot pieces", "1.5 cups water", "Pinch of turmeric", "1 tsp ghee"],
    steps: [
      "Soaking bajra is essential — it is a very hard grain. Rinse after soaking.",
      "Pressure cook everything except ghee for 5–6 whistles until completely soft.",
      "Mash very thoroughly — bajra can stay gritty, so mash more than you think needed.",
      "Stir in ghee and rest 5 minutes before serving.",
    ],
    texture69: "Wait until 9 months. Mash extra-smooth — check for any hard grains before serving.",
    texture912: "Well-mashed khichdi; it should feel creamy, never gritty.",
    texture12Plus: "Bajra khichdi with kadhi (yogurt curry) and ghee — the Rajasthani way.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Outstanding iron and magnesium plus warming energy. Traditionally eaten in winter for strength.",
    isFirstFood: false,
    baseFoodSlugs: ["moong-dal", "carrot", "butternut-squash", "ghee"],
    tips: "If bajra stays gritty after cooking, blend briefly — texture matters more than tradition for babies.",
  },
  {
    title: "Mild Palak Paneer",
    slug: "mild-palak-paneer",
    region: "North Indian",
    category: "Sides",
    foodGroup: "Dairy",
    emoji: "🧀",
    description: "Silky spinach curry with soft paneer cubes — all the restaurant flavor, zero chili, baby-soft textures.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 25, spiceLevel: "Very mild",
    ingredients: ["1 cup spinach, blanched", "50g soft paneer cubes", "1 small tomato, chopped", "1/2 tsp ginger-garlic paste", "1/4 tsp cumin", "1 tbsp milk", "1 tsp ghee"],
    steps: [
      "Blanch spinach 2 minutes, refresh in cold water, and puree smooth.",
      "Soften tomato and ginger-garlic with cumin until jammy.",
      "Add spinach puree and milk; simmer 5 minutes.",
      "Add paneer cubes and warm through 3 minutes. Mash or cut tiny for babies.",
    ],
    texture69: "Wait until 10 months. Then blend smooth-ish with tiny paneer crumbles.",
    texture912: "Soft paneer crumbles in silky spinach gravy over rice.",
    texture12Plus: "Regular palak paneer with rice, roti, or naan.",
    allergens: "Dairy",
    nutritionBenefits: "Iron and folate from spinach with calcium and protein from paneer — plus tomato's vitamin C aids iron absorption.",
    isFirstFood: false,
    baseFoodSlugs: ["spinach", "paneer", "tomato", "garlic", "ghee"],
    tips: "Blanching spinach keeps it bright green and removes oxalic sharpness babies dislike.",
  },
  {
    title: "Jowar Roti with Dal",
    slug: "jowar-roti-dal",
    region: "Karnataka",
    category: "Mains",
    foodGroup: "Millets",
    emoji: "🫓",
    description: "Soft sorghum flatbread torn and soaked in warm dal until spoon-soft — a traditional millet meal made baby-safe.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["1/2 cup jowar (sorghum) flour", "Hot water as needed", "1/2 cup warm cooked toor dal", "1 tsp ghee"],
    steps: [
      "Knead jowar flour with hot (not boiling) water into a soft, pliable dough. Rest 10 minutes.",
      "Roll small thick rotis between plastic sheets or with generous flour.",
      "Cook on a hot tawa with ghee until soft spots appear — keep them soft, not crisp.",
      "Tear into tiny pieces and SOAK in warm dal for 5 minutes before serving. Never serve dry roti pieces to babies.",
    ],
    texture69: "Wait until 10 months. Only serve dal-soaked, spoon-soft pieces — never dry or chewy bits.",
    texture912: "Small soaked pieces baby can scoop; pieces should fall apart in the mouth.",
    texture12Plus: "Soft roti pieces with dal, or let your toddler tear and dip like the family.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Gluten-free whole-grain millet rich in fiber, iron, and protein. Soaking in dal adds complete protein.",
    isFirstFood: false,
    baseFoodSlugs: ["toor-dal", "ghee"],
    tips: "Dry roti is a choking risk for babies — the 5-minute dal soak is non-negotiable under 12 months.",
  },
  {
    title: "Banana Paniyaram",
    slug: "banana-paniyaram",
    region: "Tamil Nadu",
    category: "Snacks & Drinks",
    foodGroup: "Fruits",
    emoji: "🍌",
    description: "Golden, fluffy banana-dosa bites from a paniyaram pan — naturally sweet with zero added sugar. Irresistible toddler snacks.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["1/2 cup dosa/idli batter", "1 very ripe banana, mashed", "Pinch of cardamom", "Ghee for greasing the pan"],
    steps: [
      "Mix batter with mashed banana and cardamom until uniform.",
      "Heat a paniyaram pan, grease each cup with ghee.",
      "Fill 3/4 full and cook on low 3–4 minutes per side until golden and cooked through.",
      "Cool completely — the centers stay molten-hot. Cut in halves for babies.",
    ],
    texture69: "Wait until 10 months. Cut into small halves; the inside should be fully cooked and fluffy.",
    texture912: "Halved paniyarams for self-feeding; soft enough to gum.",
    texture12Plus: "Whole paniyarams as lunchbox snacks; try a savory version with carrot and coriander.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "Fermented grains for gut health plus potassium and energy from banana — a genuinely wholesome sweet treat.",
    isFirstFood: false,
    baseFoodSlugs: ["banana", "rice", "ghee"],
    tips: "No paniyaram pan? Cook silver-dollar pancakes on a tawa instead — same batter, same joy.",
  },
  {
    title: "Sweet Pongal (Light Festive)",
    slug: "sweet-pongal-light",
    region: "Tamil Nadu",
    category: "Snacks & Drinks",
    foodGroup: "Grains",
    emoji: "🍚",
    description: "Pongal-festival sweetness with a light hand on jaggery — a celebratory taste of tradition in small portions.",
    ageMinMonths: 12, ageText: "12 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["2 tbsp rice + 1 tbsp moong dal, cooked very soft", "1 tbsp jaggery melted in 2 tbsp water, strained", "1 tsp ghee", "Pinch of cardamom"],
    steps: [
      "Cook rice and dal together until very soft and creamy.",
      "Melt jaggery in water on low heat and strain out any impurities.",
      "Combine everything with ghee and cardamom; warm through 2 minutes.",
      "Serve a SMALL portion warm — this is festive food, not everyday food.",
    ],
    texture69: "Wait until 12 months — jaggery is added sugar. Then serve soft and warm in small portions.",
    texture912: "Wait until 12 months for any jaggery or sugar.",
    texture12Plus: "Small festive portions; adults can enjoy sweeter versions separately.",
    allergens: "Dairy (ghee)",
    nutritionBenefits: "The rice-dal base is nutritious; jaggery adds trace iron but should stay an occasional treat, not a health food.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "moong-dal", "jaggery", "ghee"],
    tips: "Festivals are for joy, not restriction — a few spoonfuls for your 1-year-old is perfectly fine. Just keep sweets occasional.",
  },
];
