import type { SeedRecipe } from "./seed-recipes";

export const seedRecipesGlobal: SeedRecipe[] = [
  // ---------------- ITALY ----------------
  {
    title: "Soft Tomato-Mascarpone Pasta",
    slug: "italy-tomato-mascarpone-pasta",
    country: "Italy", cuisine: "Italian", region: "Pan-Italian",
    category: "Mains", foodGroup: "Grains", emoji: "🍝",
    description: "Silky tomato sauce folded through mascarpone and tossed with very soft pasta — a gentle first taste of Italy. No salt, all comfort.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 25, spiceLevel: "None",
    ingredients: ["1/2 cup small pasta (penne, fusilli, or farfalle)", "1 cup chopped ripe tomatoes", "2 tbsp mascarpone", "1 tsp olive oil", "1 small garlic clove, minced", "Fresh basil leaf, finely chopped (optional)"],
    steps: [
      "Cook pasta in unsalted water until very soft — 2–3 minutes past the package time.",
      "Sauté garlic in olive oil 30 seconds, add tomatoes, and simmer 10 minutes until melted.",
      "Blend or mash the sauce smooth; stir in mascarpone off the heat.",
      "Toss pasta through the sauce with a splash of pasta water. Cool to lukewarm.",
    ],
    texture69: "Wait until 7 months. Mash pasta well into the sauce or use tiny pastina stars.",
    texture912: "Soft pasta shapes fully coated in sauce; cut long shapes short.",
    texture12Plus: "Regular pasta with sauce, plus grated parmesan and garlic bread soldiers.",
    allergens: "Wheat (gluten), Dairy",
    nutritionBenefits: "Vitamin C and lycopene from tomato (cooking multiplies lycopene), calcium from mascarpone, and energy from pasta.",
    isFirstFood: false,
    baseFoodSlugs: ["pasta", "tomato", "garlic", "cheese", "olive-oil"],
    tips: "Cook a big batch of sauce and freeze in ice-cube trays — instant pasta nights for weeks.",
  },
  {
    title: "Pea & Pumpkin Risotto",
    slug: "italy-pea-pumpkin-risotto",
    country: "Italy", cuisine: "Italian", region: "Lombardy",
    category: "Mains", foodGroup: "Grains", emoji: "🍚",
    description: "Creamy arborio rice slowly stirred with sweet pumpkin and peas — naturally creamy with no cream needed. A perfect vegetarian iron-plus-vitamin-A meal.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["1/4 cup arborio or any short-grain rice", "1/2 cup pumpkin cubes", "2 tbsp peas", "1.5 cups warm water or low-sodium veg stock (homemade)", "1 tsp butter", "1 tbsp grated parmesan (optional, 10m+)"],
    steps: [
      "Simmer pumpkin in the water/stock until soft, about 10 minutes; mash half of it into the liquid.",
      "Add rice and cook on low, stirring often, adding liquid gradually — about 20 minutes until creamy and very soft.",
      "Stir in peas for the last 5 minutes.",
      "Finish with butter (and parmesan for older babies). Rest 3 minutes — it thickens as it sits.",
    ],
    texture69: "Wait until 8 months. Serve loose and creamy — risotto should spread, not stack.",
    texture912: "Creamy spoonfuls with soft pea and pumpkin pieces for chewing practice.",
    texture12Plus: "Classic risotto texture with parmesan; try mushroom or tomato versions.",
    allergens: "Dairy",
    nutritionBenefits: "Vitamin A from pumpkin, plant protein and iron from peas, and sustained energy from creamy rice.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "peas", "butternut-squash", "butter", "cheese"],
    tips: "No arborio? Any short-grain or sona masoori rice works — the starch is what makes it creamy.",
  },
  // ---------------- FRANCE ----------------
  {
    title: "Ratatouille Mash",
    slug: "france-ratatouille-mash",
    country: "France", cuisine: "French", region: "Provence",
    category: "Sides", foodGroup: "Vegetables", emoji: "🍅",
    description: "Provençal sunshine in a bowl — eggplant, zucchini, tomato, and bell pepper slow-cooked until melting, then mashed. Five vegetables, one dish.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 40, spiceLevel: "None",
    ingredients: ["1/2 zucchini + 1/4 eggplant + 1 tomato, diced small", "1/4 bell pepper, diced small", "1 tbsp minced onion", "1 tsp olive oil", "Pinch of dried herbs (thyme or basil)"],
    steps: [
      "Soften onion in olive oil 3 minutes until sweet.",
      "Add all vegetables with herbs and 1/4 cup water. Cover and simmer 25 minutes until completely melting.",
      "Mash to the texture your baby needs — chunky or smooth.",
      "Serve with soft bread, rice, or stirred into pasta.",
    ],
    texture69: "Wait until 7 months. Mash smooth-ish; the vegetables should offer zero resistance.",
    texture912: "Rustically mashed with soft chunks; mix into rice or couscous.",
    texture12Plus: "Chunky ratatouille as a side, on toast with cheese, or with an omelet.",
    allergens: "None common",
    nutritionBenefits: "Five vegetables deliver vitamin A, vitamin C, fiber, and antioxidants — plus olive oil helps absorb them all.",
    isFirstFood: false,
    baseFoodSlugs: ["zucchini", "eggplant", "tomato", "bell-pepper", "olive-oil"],
    tips: "Ratatouille tastes even better the next day — make double and refrigerate half.",
  },
  {
    title: "Soft Chicken Blanquette",
    slug: "france-chicken-blanquette",
    country: "France", cuisine: "French", region: "Île-de-France",
    category: "Mains", foodGroup: "Meat", emoji: "🍗",
    description: "France's gentlest stew — poached chicken and soft vegetables in a silky yogurt-thickened sauce. No cream, no fuss, all tenderness.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["100g boneless chicken thigh", "1 carrot + 1 small potato, cut small", "2 tbsp peas", "1.5 cups water", "2 tbsp plain yogurt", "1 tsp butter", "Bay leaf (remove before serving)"],
    steps: [
      "Simmer chicken with carrot, potato, and bay in water 20 minutes until everything is very tender.",
      "Lift out the chicken and shred finely; discard bay leaf.",
      "Whisk yogurt with a ladle of hot broth, then stir back in with butter for a silky sauce.",
      "Return shredded chicken and mash vegetables into the sauce. Serve over soft rice.",
    ],
    texture69: "Wait until 9 months. Finely shredded chicken in plenty of sauce with mashed veg.",
    texture912: "Small shreds and soft veggie pieces in creamy sauce over rice.",
    texture12Plus: "Bite-size pieces French-bistro style with rice or soft bread for mopping.",
    allergens: "Dairy",
    nutritionBenefits: "Heme iron and zinc from chicken, vitamin A from carrot, and protein from yogurt — a complete growth meal.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "carrot", "sweet-potato", "peas", "yogurt", "butter"],
    tips: "Tempering the yogurt with hot broth first stops it splitting — the key blanquette skill.",
  },
  // ---------------- SPAIN ----------------
  {
    title: "Tortilla de Patatas Fingers",
    slug: "spain-tortilla-patatas",
    country: "Spain", cuisine: "Spanish", region: "Andalusia",
    category: "Breakfast", foodGroup: "Eggs", emoji: "🍳",
    description: "Spain's beloved potato omelet, baked soft and cut into graspable fingers. Just potato, egg, onion, and olive oil — naturally baby-perfect.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["1 potato, peeled and thinly sliced", "2 tbsp minced onion", "2 eggs, beaten", "1 tbsp olive oil"],
    steps: [
      "Soften potato slices and onion in olive oil on low heat 12 minutes — no browning, just tender.",
      "Pour over beaten eggs and cook gently until nearly set, then flip (or grill the top) until fully cooked with NO runny parts.",
      "Cool 5 minutes, then cut into adult-finger-sized strips.",
      "Serve warm or room temperature — tortilla is traditionally served cool.",
    ],
    texture69: "Wait until 8 months. Cut into soft fingers; crumble smaller pieces for pincer practice.",
    texture912: "Fingers and cubes for self-feeding; stuff into soft bread rolls.",
    texture12Plus: "Tortilla wedges in lunchboxes, with tomato salad or as sandwich filling.",
    allergens: "Egg",
    nutritionBenefits: "Choline and iron from egg plus potassium and energy from potato, cooked in heart-healthy olive oil.",
    isFirstFood: false,
    baseFoodSlugs: ["egg", "sweet-potato", "olive-oil"],
    tips: "The flip is the only tricky part — slide onto a plate, invert the pan over it, and flip confidently.",
  },
  {
    title: "Chicken & Veggie Paella-Style Rice",
    slug: "spain-chicken-paella-rice",
    country: "Spain", cuisine: "Spanish", region: "Valencia",
    category: "Mains", foodGroup: "Grains", emoji: "🥘",
    description: "Golden turmeric rice with shredded chicken, peas, and sweet peppers — all the color and joy of paella with zero spice heat.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["1/4 cup short-grain rice", "80g chicken thigh, diced small", "2 tbsp peas", "1/4 red bell pepper, diced small", "1 small tomato, grated", "1/4 tsp turmeric (for golden color)", "1.5 cups water", "1 tsp olive oil"],
    steps: [
      "Sauté chicken in olive oil 3 minutes; add tomato and turmeric, cook 2 minutes.",
      "Add rice, pepper, and water. Simmer covered 20 minutes until rice is very soft (softer than adult paella).",
      "Stir in peas for the last 5 minutes. Rest 5 minutes.",
      "Shred any chicken pieces finely and fluff the rice before serving.",
    ],
    texture69: "Wait until 9 months. Rice should be soft and moist, chicken shredded fine.",
    texture912: "Soft scoopable rice with small chicken and veggie pieces.",
    texture12Plus: "Fluffy paella-style rice; add lemon wedges and let your toddler squeeze.",
    allergens: "None common",
    nutritionBenefits: "Complete meal: protein and iron from chicken, vitamin A and C from peppers and peas, energy from rice.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "chicken", "peas", "bell-pepper", "tomato", "olive-oil"],
    tips: "Turmeric gives saffron's golden color for pennies — save real saffron for adult portions.",
  },
  // ---------------- GREECE ----------------
  {
    title: "Red Lentil Fakes Soup",
    slug: "greece-fakes-lentil-soup",
    country: "Greece", cuisine: "Greek", region: "Pan-Hellenic",
    category: "Mains", foodGroup: "Legumes", emoji: "🍲",
    description: "Greece's national lentil soup — red lentils simmered with carrot, tomato, and olive oil until velvety. Simple, iron-rich, and beloved by Greek babies.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["1/4 cup red lentils, rinsed", "1 carrot, diced", "1 small tomato, chopped", "1 tbsp minced onion", "1.5 cups water", "1 tbsp olive oil", "Squeeze of lemon (12m+)"],
    steps: [
      "Soften onion and carrot in half the olive oil 4 minutes.",
      "Add lentils, tomato, and water; simmer 20–25 minutes until lentils dissolve.",
      "Blend or mash to desired smoothness.",
      "Finish with remaining olive oil (and lemon for 12m+). Serve with soft bread.",
    ],
    texture69: "Wait until 7 months. Blend silky-smooth and thin with water if needed.",
    texture912: "Thick hearty soup with soft lentil texture; great for spoon practice.",
    texture12Plus: "Classic fakes with olive oil, lemon, and crusty bread for dipping.",
    allergens: "None common",
    nutritionBenefits: "Top-tier plant iron and folate from lentils; tomato and lemon vitamin C multiplies iron absorption.",
    isFirstFood: false,
    baseFoodSlugs: ["lentils", "carrot", "tomato", "olive-oil"],
    tips: "Fakes thickens overnight — thin with water when reheating and it is good as new.",
  },
  {
    title: "Chicken Avgolemono Rice Soup",
    slug: "greece-chicken-avgolemono",
    country: "Greece", cuisine: "Greek", region: "Pan-Hellenic",
    category: "Mains", foodGroup: "Meat", emoji: "🍲",
    description: "Silky Greek chicken-and-rice soup thickened with egg and lemon — creamy without cream, bright, and soothing when appetite is low.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["80g chicken thigh", "2 tbsp rice", "2 cups water", "1 egg, beaten", "1 tsp lemon juice (12m+; skip for younger)", "1 tsp olive oil"],
    steps: [
      "Simmer chicken and rice in water 20 minutes until both are very soft.",
      "Shred the chicken finely and return to the pot.",
      "Whisk the beaten egg with a ladle of hot broth, then drizzle back in while stirring — the soup turns silky.",
      "Warm through 2 minutes without boiling. Add lemon only for 12m+.",
    ],
    texture69: "Wait until 9 months. Thin silky soup with finely shredded chicken and soft rice.",
    texture912: "Sippable from a cup plus spoonable rice-chicken; comforting and easy.",
    texture12Plus: "Classic avgolemono with lemon, dill, and bread — full taverna vibes.",
    allergens: "Egg",
    nutritionBenefits: "Heme iron from chicken, choline from egg, and hydrating broth — ideal during colds or teething.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "rice", "egg", "olive-oil"],
    tips: "Never boil after adding egg or it scrambles — gentle heat is the whole secret.",
  },
  // ---------------- UK (adapted) ----------------
  {
    title: "Turkey Shepherd's Pie",
    slug: "uk-turkey-shepherds-pie",
    country: "United Kingdom", cuisine: "British", region: "England",
    category: "Mains", foodGroup: "Meat", emoji: "🥧",
    description: "Creamy mashed potato over savory turkey and vegetable mince — cozy British comfort in a bowl. Adapted with turkey for little ones.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 45, spiceLevel: "None",
    ingredients: ["100g ground turkey (thigh mince stays juiciest)", "1 potato, peeled and cubed", "1 carrot + 2 tbsp peas, diced small", "2 tbsp minced onion", "1/2 cup water or homemade stock", "1 tsp butter + 1 tbsp milk for mash"],
    steps: [
      "Boil potato until very soft; mash with butter and milk until creamy.",
      "Brown turkey with onion 5 minutes, breaking it very fine.",
      "Add carrot, peas, and water; simmer 15 minutes until vegetables are soft and mixture is saucy.",
      "For babies: layer mince in a small dish, top with mash, and warm through 5 minutes. Cool well.",
    ],
    texture69: "Wait until 10 months. Mash the mince layer well and serve loose with extra mash.",
    texture912: "Soft layered pie baby can scoop; mince should be finely broken.",
    texture12Plus: "Classic pie slices with a golden top (grill briefly); green beans on the side.",
    allergens: "Dairy",
    nutritionBenefits: "Iron and zinc from turkey, vitamin A from carrot, potassium from potato — a balanced one-dish meal.",
    isFirstFood: false,
    baseFoodSlugs: ["turkey", "sweet-potato", "carrot", "peas", "butter"],
    tips: "Use thigh mince, not breast — breast mince bakes dry and chalky for babies.",
    isAdapted: true,
    adaptedNote: "Adapted for babies: the traditional lamb-mince pie is remade here with soft, juicy turkey and no added salt.",
  },
  // ---------------- MEXICO ----------------
  {
    title: "Black Bean & Sweet Potato Mash",
    slug: "mexico-bean-sweet-potato-mash",
    country: "Mexico", cuisine: "Mexican", region: "Oaxaca",
    category: "Mains", foodGroup: "Legumes", emoji: "🍠",
    description: "Creamy black beans mashed with caramel-sweet roasted sweet potato and a whisper of cumin — Mexican flavors, zero heat.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["1 sweet potato", "1/2 cup cooked black beans, rinsed well", "Pinch of cumin", "1 tsp olive oil", "Squeeze of lime (12m+)"],
    steps: [
      "Roast sweet potato at 400°F until collapsing soft, about 25 minutes; scoop the flesh.",
      "Warm beans with cumin and olive oil 3 minutes.",
      "Mash together to desired texture — smooth or chunky.",
      "Serve with soft rice, avocado slices, or in a soft tortilla (12m+, torn small).",
    ],
    texture69: "Wait until 7 months. Mash completely smooth; thin with warm water if needed.",
    texture912: "Chunky mash for scooping; black bean pieces should smash easily.",
    texture12Plus: "Burrito bowls, soft tacos, and quesadilla filling — full fiesta mode.",
    allergens: "None common",
    nutritionBenefits: "Iron and fiber from beans, vitamin A from sweet potato — a vegetarian complete-protein combo with rice.",
    isFirstFood: false,
    baseFoodSlugs: ["black-beans", "sweet-potato", "olive-oil"],
    tips: "Double the beans and freeze half — they thaw perfectly for next week's bowls.",
  },
  {
    title: "Soft Chicken Quesadilla Strips",
    slug: "mexico-chicken-quesadilla",
    country: "Mexico", cuisine: "Mexican", region: "Pan-Mexican",
    category: "Mains", foodGroup: "Meat", emoji: "🫓",
    description: "Shredded chicken and melted cheese folded in a soft flour tortilla — crispy-chewy for adults, made soft and strip-cut for babies.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 15, spiceLevel: "None",
    ingredients: ["1 small soft flour tortilla", "2 tbsp finely shredded cooked chicken", "2 tbsp grated low-sodium mozzarella", "1 tbsp mashed black beans (optional binder)"],
    steps: [
      "Spread beans (if using) on half the tortilla; top with chicken and cheese.",
      "Fold and cook in a dry pan 2 minutes per side until cheese just melts — keep it SOFT, not crisp.",
      "Cool 3 minutes (cheese stays molten), then cut into adult-finger strips.",
      "Serve with mashed avocado or mild salsa for 12m+.",
    ],
    texture69: "Wait until 10 months. Serve warm soft strips; ensure cheese is melted, never rubbery strings.",
    texture912: "Soft strips for holding and biting; the melted cheese binds everything.",
    texture12Plus: "Triangle-cut quesadillas with guacamole, beans, and corn on the side.",
    allergens: "Wheat (gluten), Dairy",
    nutritionBenefits: "Protein and calcium from cheese, iron from chicken — plus endless veggie-fill options as baby grows.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "cheese", "bread", "black-beans", "avocado"],
    tips: "Low-sodium mozzarella melts best and keeps salt down — pre-shredded bags work fine.",
  },
  // ---------------- USA ----------------
  {
    title: "Baked Salmon Cakes",
    slug: "usa-salmon-cakes",
    country: "United States", cuisine: "American", region: "Pacific Northwest",
    category: "Mains", foodGroup: "Fish/Seafood", emoji: "🐟",
    description: "Crispy-outside, tender-inside salmon patties with sweet potato binder — a freezer-friendly way to serve fish weekly.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["1 can boneless salmon (or 150g cooked salmon), drained", "1/2 cup mashed sweet potato", "1 egg yolk (whole egg for 12m+ patties)", "2 tbsp breadcrumbs", "1 tsp olive oil"],
    steps: [
      "Mix salmon, sweet potato, egg, and breadcrumbs; rest 5 minutes.",
      "Form small patties (baby-fist size) with damp hands.",
      "Bake at 400°F with a brush of oil, 12–15 minutes, flipping once — golden outside, moist inside.",
      "Cool well and cut into strips. Serve with yogurt dip or avocado.",
    ],
    texture69: "Wait until 9 months. Flake into small moist pieces; inside must be soft, never dry.",
    texture912: "Strips and small patties for self-feeding with dips.",
    texture12Plus: "Burger-size cakes in buns, lunchbox patties, or salad toppers.",
    allergens: "Fish, Egg, Wheat (gluten, if breadcrumbs used)",
    nutritionBenefits: "Brain-building DHA omega-3s, vitamin D, and protein — plus vitamin A from the sweet potato binder.",
    isFirstFood: false,
    baseFoodSlugs: ["salmon", "sweet-potato", "egg", "bread", "olive-oil"],
    tips: "Freeze baked cakes between parchment sheets — reheat from frozen at 375°F for 12 minutes.",
  },
  {
    title: "Turkey Meatballs with Veggie Sauce",
    slug: "usa-turkey-meatballs",
    country: "United States", cuisine: "American", region: "Pan-American",
    category: "Mains", foodGroup: "Meat", emoji: "🍝",
    description: "Juicy turkey-zucchini meatballs simmered in sweet tomato-carrot sauce — the batch-cook hero every parent needs.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 40, spiceLevel: "None",
    ingredients: ["250g ground turkey (thigh)", "1/4 cup finely grated zucchini, squeezed dry", "2 tbsp breadcrumbs", "1 egg yolk", "1 cup tomato-carrot sauce (tomatoes + carrot simmered soft)"],
    steps: [
      "Mix turkey, zucchini, breadcrumbs, and egg gently — overmixing makes tough balls.",
      "Roll mini balls (walnut size) with damp hands.",
      "Bake at 400°F for 15 minutes until cooked through (160°F inside).",
      "Simmer in warm veggie sauce 5 minutes. Halve or quarter for babies.",
    ],
    texture69: "Wait until 9 months. Quarter balls; they should crumble softly, never bounce.",
    texture912: "Halved meatballs in sauce over soft pasta or rice.",
    texture12Plus: "Meatball subs (soft rolls), spaghetti night, or lunchbox skewers.",
    allergens: "Egg, Wheat (gluten, if breadcrumbs used)",
    nutritionBenefits: "Lean protein, iron, zinc, and selenium from turkey; hidden veggies keep them juicy and vitamin-rich.",
    isFirstFood: false,
    baseFoodSlugs: ["turkey", "zucchini", "egg", "bread", "tomato", "carrot"],
    tips: "The grated zucchini is the juiciness secret — never skip it with lean turkey.",
  },
  // ---------------- BRAZIL ----------------
  {
    title: "Black Bean Stew (Feijão) with Rice",
    slug: "brazil-feijao-rice",
    country: "Brazil", cuisine: "Brazilian", region: "Pan-Brazilian",
    category: "Mains", foodGroup: "Legumes", emoji: "🫘",
    description: "Brazil's everyday miracle — silky black beans with garlic and bay over fluffy rice. Iron-rich, cheap, and deeply comforting.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 40, spiceLevel: "None",
    ingredients: ["1/2 cup dried black beans (soaked overnight) or 1 cup cooked", "1 garlic clove, minced", "1 bay leaf", "3 cups water", "1 tsp olive oil", "Soft cooked rice, to serve"],
    steps: [
      "Simmer soaked beans with bay and water 30–35 minutes (or pressure cook 12 minutes) until very soft.",
      "Sauté garlic in olive oil 30 seconds; stir in a ladle of beans, mash, and return to the pot — this thickens the broth.",
      "Simmer 5 more minutes. Remove bay leaf.",
      "Serve beans and broth over soft rice, mashing beans for younger babies.",
    ],
    texture69: "Wait until 8 months. Mash beans well into the brothy rice.",
    texture912: "Soft whole beans in broth over rice — great spoon practice.",
    texture12Plus: "Classic feijão with rice, orange slices, and sautéed greens (couve).",
    allergens: "None common",
    nutritionBenefits: "Outstanding iron, folate, and fiber; rice + beans form complete protein. Orange slices (12m+) boost iron uptake.",
    isFirstFood: false,
    baseFoodSlugs: ["black-beans", "rice", "garlic", "olive-oil"],
    tips: "Always remove the bay leaf — and count that you removed it! Whole spices hide in bean pots.",
  },
  // ---------------- PERU ----------------
  {
    title: "Chicken Quinoa Stew",
    slug: "peru-chicken-quinoa-stew",
    country: "Peru", cuisine: "Peruvian", region: "Andes",
    category: "Mains", foodGroup: "Grains", emoji: "🌾",
    description: "Andean superfood stew — fluffy quinoa, shredded chicken, and sweet vegetables in a golden turmeric broth.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["2 tbsp quinoa, rinsed very well", "80g chicken thigh", "1 carrot + 1/4 cup pumpkin, diced", "1.5 cups water", "Pinch of turmeric", "1 tsp olive oil"],
    steps: [
      "Simmer chicken in water 10 minutes; lift out and shred finely.",
      "Add quinoa, vegetables, and turmeric to the broth; simmer 15 minutes until quinoa tails pop and veg is soft.",
      "Return chicken; rest 5 minutes (quinoa keeps absorbing).",
      "Mash lightly for younger babies; serve warm, never dry.",
    ],
    texture69: "Wait until 8 months. Mash quinoa-veg well; keep it brothy and spoon-soft.",
    texture912: "Soft stew baby can scoop; tiny quinoa grains are great texture exposure.",
    texture12Plus: "Hearty bowls with avocado slices and a squeeze of lime.",
    allergens: "None common",
    nutritionBenefits: "Quinoa is a complete protein with iron and magnesium; chicken adds heme iron; orange veg adds vitamin A.",
    isFirstFood: false,
    baseFoodSlugs: ["quinoa", "chicken", "carrot", "butternut-squash", "olive-oil"],
    tips: "Rinsing quinoa well removes its bitter coating — the #1 reason people think they dislike it.",
  },
  // ---------------- ARGENTINA (adapted) ----------------
  {
    title: "Chicken Empanada Filling",
    slug: "argentina-chicken-empanada",
    country: "Argentina", cuisine: "Argentine", region: "Pampas",
    category: "Sides", foodGroup: "Meat", emoji: "🥟",
    description: "Sweet onion, soft chicken, and peas — the heart of an empanada without the hard pastry. Adapted with chicken for babies.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 25, spiceLevel: "None",
    ingredients: ["100g chicken thigh, minced fine", "2 tbsp minced onion", "2 tbsp peas", "1 small tomato, peeled and chopped", "1 tsp olive oil", "Pinch of cumin"],
    steps: [
      "Soften onion in olive oil 4 minutes until sweet and golden.",
      "Add chicken, breaking it very fine; cook 5 minutes.",
      "Add tomato, peas, cumin, and 1/4 cup water; simmer 10 minutes until saucy and soft.",
      "Serve over rice, in soft tortillas (12m+), or as a pasta sauce.",
    ],
    texture69: "Wait until 10 months. Mince should be finely broken and saucy, never chewy.",
    texture912: "Small saucy spoonfuls over soft grains.",
    texture12Plus: "Fill soft pastry or tortillas; bake mini empanadas with a fork-crimped edge.",
    allergens: "None common",
    nutritionBenefits: "Iron and protein from chicken, lycopene from tomato, and fiber from peas — endlessly versatile.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "peas", "tomato", "olive-oil"],
    tips: "This filling freezes brilliantly — portion into muffin tins for perfect single servings.",
    isAdapted: true,
    adaptedNote: "Adapted for babies: the traditional red-meat empanada filling is remade here with soft minced chicken and no added salt.",
  },
  // ---------------- MOROCCO ----------------
  {
    title: "Chicken Tagine with Apricot & Chickpeas",
    slug: "morocco-chicken-tagine",
    country: "Morocco", cuisine: "Moroccan", region: "Atlas Mountains",
    category: "Mains", foodGroup: "Meat", emoji: "🍗",
    description: "Fall-apart chicken with caramel-sweet apricots, creamy chickpeas, and warm cinnamon — Moroccan magic with zero heat.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 40, spiceLevel: "Very mild",
    ingredients: ["100g chicken thigh pieces", "1/4 cup cooked chickpeas", "2 dried apricots, chopped tiny", "2 tbsp minced onion", "Pinch each of cinnamon, turmeric, cumin", "1 cup water", "1 tsp olive oil"],
    steps: [
      "Soften onion in olive oil 4 minutes; add spices and stir 30 seconds until fragrant.",
      "Add chicken and water; simmer covered 20 minutes.",
      "Add chickpeas and apricots; simmer 10 more minutes until chicken shreds and sauce thickens.",
      "Shred chicken finely, smash chickpeas, and serve over couscous or rice.",
    ],
    texture69: "Wait until 9 months. Shredded chicken, smashed chickpeas, plenty of sauce.",
    texture912: "Small pieces in sweet-savory sauce over soft grains.",
    texture12Plus: "Tagine bowls with couscous, yogurt, and fresh coriander.",
    allergens: "None common",
    nutritionBenefits: "Heme iron from chicken plus plant iron from chickpeas; apricots add vitamin A and natural sweetness.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "chickpeas", "olive-oil"],
    tips: "Dried apricots must be chopped tiny and cooked soft — they swell and can be sticky for babies.",
  },
  {
    title: "Soft Veggie Couscous",
    slug: "morocco-veggie-couscous",
    country: "Morocco", cuisine: "Moroccan", region: "Pan-Moroccan",
    category: "Sides", foodGroup: "Grains", emoji: "🍚",
    description: "Fluffy pearls of couscous steamed over sweet vegetables — ready in 15 minutes and endlessly customizable.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["1/4 cup couscous", "1/2 cup soft-cooked diced veg (carrot, zucchini, pumpkin)", "1/2 cup hot water or homemade stock", "1 tsp olive oil", "Pinch of cumin"],
    steps: [
      "Pour hot water over couscous with olive oil; cover 5 minutes, then fluff — grains should be soft, not al dente.",
      "Fold through the soft vegetables and cumin.",
      "Add a splash more warm water if it looks dry — baby couscous should be moist.",
      "Serve with yogurt, lentils, or shredded chicken.",
    ],
    texture69: "Wait until 8 months. Moist and clumpy (not separate grains); mix with yogurt to bind.",
    texture912: "Fluffy spoonfuls; great for practicing scooping.",
    texture12Plus: "Couscous salads, tagine bases, and lunchbox grains.",
    allergens: "Wheat (gluten)",
    nutritionBenefits: "Quick energy plus B vitamins; the colorful vegetables add fiber and antioxidants.",
    isFirstFood: false,
    baseFoodSlugs: ["pasta", "carrot", "zucchini", "butternut-squash", "olive-oil", "yogurt"],
    tips: "Couscous contains wheat — it counts as a wheat-allergen exposure. Serve in the morning the first time.",
  },
  // ---------------- EGYPT ----------------
  {
    title: "Red Lentil Koshari-Style Bowl",
    slug: "egypt-koshari-bowl",
    country: "Egypt", cuisine: "Egyptian", region: "Cairo",
    category: "Mains", foodGroup: "Legumes", emoji: "🍚",
    description: "Egypt's legendary street-food combo — rice, lentils, and soft pasta under sweet tomato sauce. Carby, cozy, and kid-approved.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["2 tbsp rice + 1 tbsp small pasta + 2 tbsp red lentils", "1 cup tomato puree (fresh or passata)", "1/2 tsp cumin", "1 tsp olive oil", "2 cups water"],
    steps: [
      "Simmer rice, pasta, and lentils in water 20–25 minutes until everything is very soft and porridge-like.",
      "Meanwhile simmer tomato puree with cumin and olive oil 10 minutes into a sweet sauce.",
      "Layer grains in a bowl and spoon sauce over. Mash together for babies.",
      "Top adult portions with crispy onions — keep baby's soft.",
    ],
    texture69: "Wait until 8 months. Mash into a soft porridge-like bowl.",
    texture912: "Thick scoopable bowl with soft textures.",
    texture12Plus: "Layered bowls with all the toppings bar: chickpeas, onions, lemon.",
    allergens: "Wheat (gluten, from pasta)",
    nutritionBenefits: "Triple-carb energy with lentil iron and protein; tomato vitamin C boosts the lentils' iron.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "pasta", "lentils", "tomato", "olive-oil"],
    tips: "One-pot version: cook everything together and add the sauce at the end — weeknight koshari!",
  },
  // ---------------- NIGERIA ----------------
  {
    title: "Mild Jollof Rice with Chicken",
    slug: "nigeria-jollof-rice",
    country: "Nigeria", cuisine: "Nigerian", region: "Lagos",
    category: "Mains", foodGroup: "Grains", emoji: "🍚",
    description: "West Africa's famous party rice — smoky-sweet tomato rice with shredded chicken. This baby version skips all heat, keeps all flavor.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 40, spiceLevel: "Very mild",
    ingredients: ["1/4 cup long-grain rice", "1/2 cup tomato-pepper blend (tomato + red bell pepper, blended)", "80g chicken thigh", "1.5 cups water", "1 tsp oil", "Pinch of thyme"],
    steps: [
      "Simmer chicken in water 15 minutes; shred finely and reserve the broth.",
      "Cook the tomato-pepper blend with oil and thyme 8 minutes until sweet and thick.",
      "Add rice and 1.5 cups broth; simmer covered 20 minutes until very soft.",
      "Fold in shredded chicken; rest 5 minutes before serving.",
    ],
    texture69: "Wait until 10 months. Rice should be soft and saucy, chicken shredded fine.",
    texture912: "Moist jollof spoonfuls; smoky-sweet flavor babies love.",
    texture12Plus: "Party jollof with fried plantain (soft, 12m+) and chicken pieces.",
    allergens: "None common",
    nutritionBenefits: "Lycopene-rich tomato base, heme iron from chicken, and energy from rice — a complete celebration meal.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "tomato", "bell-pepper", "chicken", "olive-oil"],
    tips: "Red bell pepper (not chili) gives jollof color without any heat — the baby-jollof secret.",
  },
  {
    title: "Moi Moi Steamed Bean Cakes",
    slug: "nigeria-moi-moi",
    country: "Nigeria", cuisine: "Nigerian", region: "Pan-Nigerian",
    category: "Sides", foodGroup: "Legumes", emoji: "🍮",
    description: "Silky steamed black-eyed-pea puddings with egg — protein-packed, spoon-soft, and naturally portion-sized.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 50, spiceLevel: "None",
    ingredients: ["1/2 cup black-eyed peas, soaked 4 hours and peeled", "1 egg", "1/4 red bell pepper", "2 tbsp minced onion", "2 tbsp oil", "1/2 cup water"],
    steps: [
      "Rub soaked peas to remove skins; rinse clean.",
      "Blend peas, pepper, onion, and water into a thick smooth batter.",
      "Whisk in egg and oil. Pour into greased ramekins or banana-leaf cups.",
      "Steam 30–35 minutes until set like savory custard. Cool before unmolding.",
    ],
    texture69: "Wait until 9 months. Spoon-soft custard; crumble into small pieces.",
    texture912: "Soft cakes baby can hold; the egg sets them perfectly for grasping.",
    texture12Plus: "Moi moi with jollof rice or pap (ogi) — the classic Nigerian combo.",
    allergens: "Egg",
    nutritionBenefits: "Double protein (beans + egg), iron, and folate in a soft, digestible steamed form.",
    isFirstFood: false,
    baseFoodSlugs: ["black-beans", "egg", "bell-pepper", "olive-oil"],
    tips: "Peeling the peas is the fiddly bit — rub in water and skins float off. Worth it for silkiness.",
  },
  // ---------------- ETHIOPIA ----------------
  {
    title: "Mild Misir Wot Red Lentils",
    slug: "ethiopia-misir-wot",
    country: "Ethiopia", cuisine: "Ethiopian", region: "Addis Ababa",
    category: "Mains", foodGroup: "Legumes", emoji: "🍲",
    description: "Velvety red lentils in a fragrant ginger-garlic-tomato base — Ethiopian comfort without the berbere heat.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 30, spiceLevel: "Very mild",
    ingredients: ["1/4 cup red lentils, rinsed", "2 tbsp minced onion", "1 tsp grated ginger", "1 small garlic clove, minced", "1 small tomato, chopped", "1.5 cups water", "1 tsp oil"],
    steps: [
      "Soften onion, ginger, and garlic in oil 5 minutes until sweet.",
      "Add tomato and cook 3 minutes until jammy.",
      "Add lentils and water; simmer 20 minutes until completely dissolved and velvety.",
      "Serve with soft injera-style flatbread pieces (12m+) or rice for younger babies.",
    ],
    texture69: "Wait until 8 months. Silky and pourable — thin with water if needed.",
    texture912: "Thick velvety lentils for scooping with soft bread or rice.",
    texture12Plus: "Full Ethiopian platter vibes: lentils + veg + soft flatbread for tearing.",
    allergens: "None common",
    nutritionBenefits: "Iron, folate, and protein from lentils; ginger and garlic traditionally aid digestion.",
    isFirstFood: false,
    baseFoodSlugs: ["lentils", "tomato", "garlic", "rice", "olive-oil"],
    tips: "Teff injera is naturally fermented and nutritious — tear into tiny soft pieces for toddlers.",
  },
  // ---------------- TURKEY (country) ----------------
  {
    title: "Red Lentil Soup (Mercimek Çorbası)",
    slug: "turkey-mercimek-soup",
    country: "Türkiye", cuisine: "Turkish", region: "Anatolia",
    category: "Mains", foodGroup: "Legumes", emoji: "🍲",
    description: "Türkiye's beloved silky lentil soup with carrot and a whisper of cumin — the soup Turkish babies grow up on.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 25, spiceLevel: "None",
    ingredients: ["1/4 cup red lentils", "1 carrot, sliced", "1 small potato, cubed", "2 tbsp minced onion", "2 cups water", "1 tsp butter or olive oil", "Pinch of cumin"],
    steps: [
      "Simmer everything except butter for 20 minutes until vegetables collapse.",
      "Blend completely silky (or mash very well).",
      "Swirl in butter and cumin.",
      "Serve with lemon for 12m+; plain and warm for babies.",
    ],
    texture69: "Wait until 7 months. Completely smooth and sippable from a cup or spoon.",
    texture912: "Slightly thicker; wonderful for dunking soft bread.",
    texture12Plus: "Classic mercimek with lemon, chili oil for adults only, and crusty bread.",
    allergens: "Dairy (if butter used)",
    nutritionBenefits: "Iron and folate from lentils, vitamin A from carrot, comfort in every spoon.",
    isFirstFood: false,
    baseFoodSlugs: ["lentils", "carrot", "sweet-potato", "butter"],
    tips: "This soup is traditionally the first soup of Ramadan fast-breaking — gentle enough for the littlest tummies too.",
  },
  {
    title: "Chicken Shish with Yogurt",
    slug: "turkey-chicken-shish",
    country: "Türkiye", cuisine: "Turkish", region: "Anatolia",
    category: "Mains", foodGroup: "Meat", emoji: "🍗",
    description: "Lemon-yogurt marinated chicken baked juicy-soft and served over yogurt — tender kebab flavors with no grill needed.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["120g chicken thigh strips", "2 tbsp yogurt + 2 tbsp more to serve", "1 tsp lemon juice (12m+; skip under 12m)", "1/2 tsp cumin", "1 tsp olive oil", "Soft flatbread or rice, to serve"],
    steps: [
      "Marinate chicken in yogurt, cumin, and oil 15+ minutes (overnight is best).",
      "Bake at 400°F for 18–20 minutes until juicy and cooked through.",
      "Rest 5 minutes, then slice across the grain into tiny bite-size pieces.",
      "Serve over yogurt with soft flatbread or rice.",
    ],
    texture69: "Wait until 10 months. Cut across the grain into tiny soft pieces; mix with yogurt.",
    texture912: "Small juicy pieces; the yogurt marinade keeps them tender.",
    texture12Plus: "Kebab plates, wraps, and lunchbox skewers (no sharp sticks for toddlers).",
    allergens: "Dairy",
    nutritionBenefits: "Protein, iron, and zinc from chicken; yogurt adds calcium and probiotics while tenderizing the meat.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "yogurt", "olive-oil", "rice"],
    tips: "Cutting across the grain (not with it) is what makes chicken easy to chew — look for the lines and cut perpendicular.",
  },
  // ---------------- LEBANON ----------------
  {
    title: "Hummus with Soft Pita",
    slug: "lebanon-hummus-pita",
    country: "Lebanon", cuisine: "Lebanese", region: "Beirut",
    category: "Snacks & Drinks", foodGroup: "Legumes", emoji: "🫘",
    description: "Extra-creamy chickpea hummus with tahini and lemon, scooped with pillowy soft pita — the world's favorite dip, baby-proofed.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 15, spiceLevel: "None",
    ingredients: ["1 cup cooked chickpeas (skins rubbed off for silkiness)", "1 tbsp tahini", "1 tbsp olive oil + more to drizzle", "1 tsp lemon juice (12m+)", "2–3 tbsp water", "Soft pita bread, torn"],
    steps: [
      "Rub chickpeas in water to loosen skins; skim them off for the creamiest hummus.",
      "Blend chickpeas, tahini, olive oil, and water 3–4 minutes until completely silky.",
      "Spread THIN (never a glob) and drizzle olive oil.",
      "Serve with torn soft pita and steamed veggie sticks for dipping.",
    ],
    texture69: "Wait until 8 months. Silky and thin — spread paper-thin on soft pita strips.",
    texture912: "Creamy dip for soft pita and steamed vegetables.",
    texture12Plus: "Hummus bowls with all the toppings; lunchbox dip with rainbow dippers.",
    allergens: "Sesame (tahini), Wheat (gluten, pita)",
    nutritionBenefits: "Protein, fiber, and iron from chickpeas; calcium and healthy fats from tahini.",
    isFirstFood: false,
    baseFoodSlugs: ["chickpeas", "tahini", "olive-oil", "bread"],
    tips: "Tahini is a sesame-allergen exposure — serve in the morning the first time and watch for 2 hours.",
  },
  {
    title: "Mujadara Lentils & Rice",
    slug: "lebanon-mujadara",
    country: "Lebanon", cuisine: "Lebanese", region: "Pan-Lebanese",
    category: "Mains", foodGroup: "Legumes", emoji: "🍚",
    description: "Caramelized-onion lentils and rice — the Middle East's humblest, most delicious vegetarian meal. Sweet, soft, and satisfying.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 40, spiceLevel: "None",
    ingredients: ["2 tbsp brown or green lentils", "2 tbsp rice", "1 onion, thinly sliced", "1.5 cups water", "1 tbsp olive oil", "Pinch of cumin"],
    steps: [
      "Caramelize onion in olive oil on low heat 15 minutes until deep golden and sweet.",
      "Add lentils, rice, cumin, and water; simmer 25 minutes until very soft.",
      "Rest 5 minutes — it firms into scoopable perfection.",
      "Serve with a dollop of yogurt.",
    ],
    texture69: "Wait until 8 months. Mash lightly; grains should be soft and sticky, not separate.",
    texture912: "Scoopable lentil-rice with sweet onion threads.",
    texture12Plus: "Classic mujadara with yogurt-cucumber salad on the side.",
    allergens: "None common (Dairy if yogurt served)",
    nutritionBenefits: "Complete protein (lentils + rice), iron, and fiber — proof that simple food is super food.",
    isFirstFood: false,
    baseFoodSlugs: ["lentils", "rice", "olive-oil", "yogurt"],
    tips: "The deeply caramelized onions are the entire dish — don't rush them; low and slow wins.",
  },
  // ---------------- ISRAEL ----------------
  {
    title: "Mild Shakshuka",
    slug: "israel-mild-shakshuka",
    country: "Israel", cuisine: "Israeli", region: "Pan-Israeli",
    category: "Breakfast", foodGroup: "Eggs", emoji: "🍳",
    description: "Eggs poached in sweet tomato-pepper sauce — brunch royalty, made baby-gentle with no chili and fully-set eggs.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["1 cup chopped tomatoes", "1/4 red bell pepper, diced", "2 tbsp minced onion", "1 egg per baby portion", "1 tsp olive oil", "Pinch of cumin"],
    steps: [
      "Soften onion and pepper in olive oil 5 minutes.",
      "Add tomatoes and cumin; simmer 8 minutes into a thick sauce.",
      "Make wells and crack in eggs; cover and cook until whites are FULLY set (no runny parts for babies).",
      "Spoon egg with plenty of sauce; mash and serve with soft bread.",
    ],
    texture69: "Wait until 9 months. Mash egg completely into the sauce.",
    texture912: "Chopped egg in sauce for scooping with soft bread soldiers.",
    texture12Plus: "Classic shakshuka with feta, herbs, and crusty bread for the table.",
    allergens: "Egg",
    nutritionBenefits: "Choline and iron from egg, lycopene and vitamin C from the tomato-pepper sauce.",
    isFirstFood: false,
    baseFoodSlugs: ["egg", "tomato", "bell-pepper", "olive-oil", "bread"],
    tips: "Baby eggs must be fully cooked — save the jammy-yolk shakshuka for adult portions.",
  },
  // ---------------- JAPAN ----------------
  {
    title: "Salmon Okayu Porridge",
    slug: "japan-salmon-okayu",
    country: "Japan", cuisine: "Japanese", region: "Pan-Japanese",
    category: "Mains", foodGroup: "Fish/Seafood", emoji: "🐟",
    description: "Japan's quintessential baby food — rice simmered into silky porridge with flakes of salmon. Okayu is literally designed for little ones.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["2 tbsp short-grain rice", "1.5 cups water", "50g salmon fillet (checked for bones)", "1 tsp finely grated carrot (optional)"],
    steps: [
      "Simmer rice in water 25 minutes, stirring occasionally, until broken and porridge-like.",
      "Poach salmon on top for the last 8 minutes; lift out and flake finely, re-checking for bones.",
      "Stir flakes back through the porridge.",
      "Cool to lukewarm — okayu holds heat, so test carefully.",
    ],
    texture69: "Wait until 7 months. Silky 10x porridge (very loose); mash any lumps.",
    texture912: "Thicker 7x porridge with visible salmon flakes.",
    texture12Plus: "Hearty okayu/zosui with egg, mushrooms, and grown-up toppings on the side.",
    allergens: "Fish",
    nutritionBenefits: "DHA omega-3s and vitamin D from salmon in the gentlest possible form — plus hydrating, easy-to-digest rice.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "salmon", "carrot"],
    tips: "Okayu ratio magic: 1:10 rice-to-water for beginners, 1:7 for older babies, 1:5 for toddlers.",
  },
  {
    title: "Chicken Tsukune Meatballs",
    slug: "japan-chicken-tsukune",
    country: "Japan", cuisine: "Japanese", region: "Pan-Japanese",
    category: "Mains", foodGroup: "Meat", emoji: "🍡",
    description: "Cloud-soft Japanese chicken meatballs with tofu and egg — so tender they barely hold together, in the best way.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 25, spiceLevel: "None",
    ingredients: ["150g ground chicken (thigh)", "2 tbsp silken tofu, drained", "1 egg yolk", "1 tsp grated ginger (squeezed — juice only for babies)", "1 tsp potato starch or cornstarch"],
    steps: [
      "Mix everything very gently until just combined.",
      "Form small ovals with damp hands.",
      "Simmer in water or dashi-style broth 8–10 minutes until cooked through and bouncy-soft.",
      "Serve in warm broth with soft rice or noodles.",
    ],
    texture69: "Wait until 9 months. Halve balls; they should be spoon-soft and juicy.",
    texture912: "Whole mini ovals in broth — perfect grasping size.",
    texture12Plus: "Tsukune skewers (adult-held) with tare sauce for dipping (low-sodium).",
    allergens: "Egg, Soy",
    nutritionBenefits: "Lean protein from chicken plus complete protein from tofu and egg — triple-source growth fuel.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "tofu", "egg", "rice"],
    tips: "Ginger juice (not the fiber) gives flavor without the burn — grate, then squeeze through your fingers.",
  },
  // ---------------- KOREA ----------------
  {
    title: "Dakjuk Chicken Porridge",
    slug: "korea-dakjuk-porridge",
    country: "South Korea", cuisine: "Korean", region: "Pan-Korean",
    category: "Mains", foodGroup: "Grains", emoji: "🍲",
    description: "Korea's healing porridge — rice simmered in chicken broth until creamy, with shredded chicken and sweet pumpkin.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["2 tbsp short-grain rice", "80g chicken thigh", "1/4 cup pumpkin cubes", "2 cups water", "1 tsp sesame oil (12m+; use olive oil under 12m)"],
    steps: [
      "Simmer chicken in water 15 minutes; shred finely and reserve broth.",
      "Cook rice and pumpkin in the broth 20 minutes, stirring often, until creamy porridge.",
      "Stir chicken back in; rest 5 minutes.",
      "Finish with age-appropriate oil and serve lukewarm.",
    ],
    texture69: "Wait until 7 months. Creamy loose porridge; mash pumpkin into it.",
    texture912: "Thicker juk with soft chicken shreds.",
    texture12Plus: "Hearty dakjuk with sesame oil, seaweed flakes, and grown-up kimchi on the side (adults only).",
    allergens: "Sesame (only if sesame oil used, 12m+)",
    nutritionBenefits: "Hydrating and easy to digest when appetite is low; chicken adds heme iron, pumpkin adds vitamin A.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "chicken", "butternut-squash", "olive-oil"],
    tips: "Dakjuk is Korea's go-to sick-day food — freeze portions for colds and teething weeks.",
  },
  // ---------------- CHINA ----------------
  {
    title: "Chicken Congee with Greens",
    slug: "china-chicken-congee",
    country: "China", cuisine: "Chinese", region: "Guangdong",
    category: "Mains", foodGroup: "Grains", emoji: "🍚",
    description: "Silky Cantonese-style rice porridge with shredded chicken and wilted greens — the first food of millions of babies.",
    ageMinMonths: 6, ageText: "6 months+", prepMinutes: 40, spiceLevel: "None",
    ingredients: ["2 tbsp jasmine or short-grain rice", "60g chicken thigh", "2 tbsp finely chopped bok choy or spinach", "2.5 cups water", "1 tsp oil", "Paper-thin ginger slice (remove before serving)"],
    steps: [
      "Simmer rice, chicken, and ginger in water 30 minutes, stirring occasionally, until rice bursts into silk.",
      "Lift out chicken; shred very finely. Discard ginger.",
      "Stir greens into the hot congee; they wilt in 2 minutes.",
      "Return chicken, drizzle oil, and cool to lukewarm.",
    ],
    texture69: "Thin silky congee that ribbons off a spoon. Pre-load spoons for self-feeding.",
    texture912: "Thicker congee with soft chicken and green flecks.",
    texture12Plus: "Congee bars with toppings: egg, fish, peanuts for adults, scallions (12m+).",
    allergens: "None common",
    nutritionBenefits: "Gentle first grains, heme iron from chicken, folate from greens — the complete first-food package.",
    isFirstFood: true,
    baseFoodSlugs: ["rice", "chicken", "spinach"],
    tips: "Frozen rice cooks into congee twice as fast — freeze cooked rice in portions for instant congee.",
  },
  {
    title: "Steamed Egg Custard",
    slug: "china-steamed-egg",
    country: "China", cuisine: "Chinese", region: "Pan-Chinese",
    category: "Sides", foodGroup: "Eggs", emoji: "🍮",
    description: "Trembling-smooth savory egg custard steamed with water until it wobbles like tofu — pure protein silk.",
    ageMinMonths: 8, ageText: "8 months+", prepMinutes: 20, spiceLevel: "None",
    ingredients: ["1 egg", "1/2 cup warm water (1:1.5 egg-to-water ratio)", "1 tsp oil", "1 tbsp minced soft shrimp (optional, 9m+)"],
    steps: [
      "Whisk egg with warm water until uniform; strain into a heatproof bowl for ultimate silkiness.",
      "Cover with a plate (stops water drips making craters) and steam on low 10–12 minutes until just set with a wobble.",
      "Rest 3 minutes — it firms as it sits.",
      "Drizzle oil and scoop with a soft spoon.",
    ],
    texture69: "Wait until 8 months. Spoon-soft custard that melts — no chewing needed.",
    texture912: "Silky scoops; add tiny shrimp or minced chicken for texture.",
    texture12Plus: "Chawanmushi-style cups with mushrooms, fish cake, and grown-up dashi flavors.",
    allergens: "Egg, Shellfish (only if shrimp added)",
    nutritionBenefits: "Complete protein, choline, and B12 in the softest possible form — ideal for new eaters.",
    isFirstFood: false,
    baseFoodSlugs: ["egg", "shrimp"],
    tips: "Low heat + covered steaming = smooth custard. High heat = honeycomb sponge (still tasty, less silky).",
  },
  // ---------------- THAILAND ----------------
  {
    title: "Mild Coconut Chicken Soup",
    slug: "thailand-coconut-chicken-soup",
    country: "Thailand", cuisine: "Thai", region: "Bangkok",
    category: "Mains", foodGroup: "Meat", emoji: "🥥",
    description: "Fragrant tom-kha-inspired soup with chicken and soft mushrooms in coconut milk — lemongrass perfume, zero chili.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 25, spiceLevel: "None",
    ingredients: ["100g chicken thigh, thinly sliced", "1/2 cup light coconut milk + 1/2 cup water", "2 mushrooms, thinly sliced", "1 stalk lemongrass, bruised (remove before serving)", "1 tsp lime juice (12m+ only)"],
    steps: [
      "Simmer lemongrass in coconut milk + water 5 minutes to infuse; remove lemongrass.",
      "Add chicken and mushrooms; simmer 12 minutes until chicken is tender.",
      "Shred or chop chicken very fine for babies.",
      "Add lime only for 12m+. Serve as soup or over soft rice.",
    ],
    texture69: "Wait until 9 months. Thin fragrant soup with finely chopped chicken and soft mushrooms.",
    texture912: "Soup with rice; mushrooms should be completely tender.",
    texture12Plus: "Tom-kha-style bowls with lime, herbs, and jasmine rice.",
    allergens: "Coconut",
    nutritionBenefits: "Protein and iron from chicken, easily-digested fats from coconut milk, B vitamins from mushrooms.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "coconut", "mushrooms", "rice"],
    tips: "Bruise lemongrass with the back of a knife to release oils — and always fish it out before serving.",
  },
  // ---------------- VIETNAM ----------------
  {
    title: "Chicken Pho Broth with Soft Noodles",
    slug: "vietnam-chicken-pho",
    country: "Vietnam", cuisine: "Vietnamese", region: "Hanoi",
    category: "Mains", foodGroup: "Meat", emoji: "🍜",
    description: "Clear, aromatic pho-style broth with star anise and ginger, soft rice noodles, and shredded chicken — soothing and slurpable.",
    ageMinMonths: 9, ageText: "9 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["100g chicken thigh", "1 star anise + 1 thin ginger slice (remove both before serving)", "1/2 cup flat rice noodles", "3 cups water", "2 tbsp finely chopped bok choy"],
    steps: [
      "Simmer chicken with star anise and ginger 20 minutes into a fragrant clear broth.",
      "Lift out chicken; shred finely. Strain and discard spices.",
      "Cook noodles in the broth until very soft (softer than adult pho); add bok choy last 2 minutes.",
      "Cut noodles short with scissors — long noodles gag babies. Serve warm in broth.",
    ],
    texture69: "Wait until 9 months. Short soft noodles in plenty of broth with finely shredded chicken.",
    texture912: "Slurpable short noodles; great chopstick-play (with fingers, realistically).",
    texture12Plus: "DIY pho bowls: herbs, bean sprouts (cooked for toddlers), lime, and hoisin (12m+).",
    allergens: "None common",
    nutritionBenefits: "Hydrating mineral-rich broth, heme iron from chicken, and gentle rice noodles for energy.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "rice", "spinach", "pasta"],
    tips: "Kitchen scissors are a baby-feeding essential — snip noodles, greens, and chicken right in the bowl.",
  },
  // ---------------- INDONESIA ----------------
  {
    title: "Bubur Ayam Chicken Porridge",
    slug: "indonesia-bubur-ayam",
    country: "Indonesia", cuisine: "Indonesian", region: "Java",
    category: "Mains", foodGroup: "Grains", emoji: "🍲",
    description: "Indonesia's beloved chicken rice porridge with turmeric and crispy-shallot spirit — savory, golden, and deeply comforting.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["2 tbsp rice", "80g chicken thigh", "2.5 cups water", "1/4 tsp turmeric", "1 tbsp finely chopped carrot", "1 tsp oil", "Soft fried shallots (12m+) or skip"],
    steps: [
      "Simmer rice, chicken, turmeric, and carrot in water 30 minutes until porridge-creamy.",
      "Shred chicken very finely and stir back in.",
      "Drizzle oil and rest 5 minutes.",
      "Top adult bowls with shallots, egg, and sambal — baby's stays plain and golden.",
    ],
    texture69: "Wait until 7 months. Golden silky porridge; pre-load spoons.",
    texture912: "Thicker porridge with soft chicken shreds.",
    texture12Plus: "Full bubur ayam bar: egg, shallots, crackers (12m+), and soy sauce (tiny amounts).",
    allergens: "None common",
    nutritionBenefits: "Turmeric's gentle anti-inflammatory compounds, heme iron from chicken, and vitamin A from carrot.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "chicken", "carrot"],
    tips: "Street-style bubur ayam has a dozen toppings — introduce them one at a time for toddlers.",
  },
  // ---------------- PHILIPPINES ----------------
  {
    title: "Chicken Arroz Caldo",
    slug: "philippines-arroz-caldo",
    country: "Philippines", cuisine: "Filipino", region: "Luzon",
    category: "Mains", foodGroup: "Grains", emoji: "🍲",
    description: "Filipino ginger-garlic chicken rice porridge with a golden egg ribbon — the ultimate comfort food for sniffly days.",
    ageMinMonths: 7, ageText: "7 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["2 tbsp glutinous or jasmine rice", "80g chicken thigh", "1 tsp grated ginger + 1 garlic clove, minced", "2.5 cups water", "1 egg, beaten (for ribbon, 8m+)", "1 tsp oil"],
    steps: [
      "Sauté ginger and garlic in oil 1 minute until fragrant (not brown).",
      "Add rice, chicken, and water; simmer 30 minutes until thick porridge.",
      "Shred chicken finely and stir back in.",
      "For 8m+: drizzle beaten egg in while stirring for silky ribbons; cook 2 more minutes.",
    ],
    texture69: "Wait until 7 months (skip egg ribbon until 8m). Thick warming porridge.",
    texture912: "Hearty porridge with egg ribbons and soft chicken.",
    texture12Plus: "Classic arroz caldo with calamansi, garlic bits, and fish sauce for adults (tiny amounts for toddlers).",
    allergens: "Egg (only if ribbon added)",
    nutritionBenefits: "Ginger and garlic traditionally comfort colds; chicken and egg deliver iron and choline.",
    isFirstFood: false,
    baseFoodSlugs: ["rice", "chicken", "garlic", "egg"],
    tips: "Glutinous (malagkit) rice makes the thickest, stickiest porridge — worth seeking out.",
  },
  // ---------------- GERMANY (adapted) ----------------
  {
    title: "Chicken Frikadellen",
    slug: "germany-chicken-frikadellen",
    country: "Germany", cuisine: "German", region: "Pan-German",
    category: "Mains", foodGroup: "Meat", emoji: "🧆",
    description: "Juicy German-style patties made with chicken, soaked bread, and sweet onion — crisp-edged, tender-centered, lunchbox-perfect. Adapted with chicken.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 30, spiceLevel: "None",
    ingredients: ["200g ground chicken (thigh)", "1 slice soft bread, soaked in 2 tbsp milk and squeezed", "2 tbsp grated onion", "1 egg yolk", "1 tsp oil + butter for frying"],
    steps: [
      "Mix chicken, soaked bread, onion, and egg gently; rest 10 minutes.",
      "Form small flat patties with damp hands.",
      "Pan-fry on medium-low 4–5 minutes per side until golden and cooked through.",
      "Cool and cut into strips. Serve with potato-carrot mash.",
    ],
    texture69: "Wait until 10 months. Cut into soft strips; inside must be juicy, never dense.",
    texture912: "Strips and small patties for holding; the soaked bread keeps them soft.",
    texture12Plus: "Frikadellen with potato salad, in rolls, or cold in lunchboxes.",
    allergens: "Egg, Wheat (gluten), Dairy",
    nutritionBenefits: "Protein and iron from chicken in a soft, high-acceptance format even cautious eaters enjoy.",
    isFirstFood: false,
    baseFoodSlugs: ["chicken", "bread", "egg", "butter"],
    tips: "Soaked bread (not dry breadcrumbs) is the German juiciness trick — panade power!",
    isAdapted: true,
    adaptedNote: "Adapted for babies: the traditional mixed-mince patty is remade here with 100% chicken and no added salt.",
  },
  // ---------------- SWEDEN (adapted) ----------------
  {
    title: "Turkey Köttbullar",
    slug: "sweden-turkey-kottbullar",
    country: "Sweden", cuisine: "Swedish", region: "Pan-Swedish",
    category: "Mains", foodGroup: "Meat", emoji: "🧆",
    description: "Little Swedish meatballs with warm allspice, served with creamy mash — all the IKEA nostalgia, made soft and juicy with turkey. Adapted for babies.",
    ageMinMonths: 10, ageText: "10 months+", prepMinutes: 35, spiceLevel: "None",
    ingredients: ["200g ground turkey (thigh)", "2 tbsp breadcrumbs soaked in 2 tbsp milk", "1 tbsp grated onion", "Tiny pinch of allspice", "1 egg yolk", "Mashed potato, to serve"],
    steps: [
      "Mix turkey, soaked crumbs, onion, allspice, and egg gently.",
      "Roll cherry-size balls with damp hands — small cooks juicier.",
      "Brown in butter on medium heat, then add a splash of water, cover, and steam 5 minutes until cooked through.",
      "Serve with creamy mash and (12m+) a spoon of lingonberry jam.",
    ],
    texture69: "Wait until 10 months. Halve balls; they should be soft and juicy throughout.",
    texture912: "Mini balls with mash — the ultimate toddler plate.",
    texture12Plus: "Full Swedish plate: köttbullar, mash, gravy, lingonberry, and pickled cucumber.",
    allergens: "Egg, Wheat (gluten), Dairy",
    nutritionBenefits: "Iron, zinc, and protein from turkey; allspice adds warm flavor without any heat.",
    isFirstFood: false,
    baseFoodSlugs: ["turkey", "bread", "egg", "butter", "sweet-potato"],
    tips: "The steam-finish (splash of water + lid) keeps lean turkey juicy — never skip it.",
    isAdapted: true,
    adaptedNote: "Adapted for babies: the traditional mixed-mince meatball is remade here with juicy turkey and baby-soft texture.",
  },
];

export const GLOBAL_COUNTRIES: { country: string; cuisine: string; flag: string }[] = [
  { country: "India", cuisine: "Indian", flag: "🇮🇳" },
  { country: "Italy", cuisine: "Italian", flag: "🇮🇹" },
  { country: "France", cuisine: "French", flag: "🇫🇷" },
  { country: "Spain", cuisine: "Spanish", flag: "🇪🇸" },
  { country: "Greece", cuisine: "Greek", flag: "🇬🇷" },
  { country: "United Kingdom", cuisine: "British", flag: "🇬🇧" },
  { country: "Germany", cuisine: "German", flag: "🇩🇪" },
  { country: "Sweden", cuisine: "Swedish", flag: "🇸🇪" },
  { country: "United States", cuisine: "American", flag: "🇺🇸" },
  { country: "Mexico", cuisine: "Mexican", flag: "🇲🇽" },
  { country: "Brazil", cuisine: "Brazilian", flag: "🇧🇷" },
  { country: "Peru", cuisine: "Peruvian", flag: "🇵🇪" },
  { country: "Argentina", cuisine: "Argentine", flag: "🇦🇷" },
  { country: "Morocco", cuisine: "Moroccan", flag: "🇲🇦" },
  { country: "Egypt", cuisine: "Egyptian", flag: "🇪🇬" },
  { country: "Nigeria", cuisine: "Nigerian", flag: "🇳🇬" },
  { country: "Ethiopia", cuisine: "Ethiopian", flag: "🇪🇹" },
  { country: "Türkiye", cuisine: "Turkish", flag: "🇹🇷" },
  { country: "Lebanon", cuisine: "Lebanese", flag: "🇱🇧" },
  { country: "Israel", cuisine: "Israeli", flag: "🇮🇱" },
  { country: "China", cuisine: "Chinese", flag: "🇨🇳" },
  { country: "Japan", cuisine: "Japanese", flag: "🇯🇵" },
  { country: "South Korea", cuisine: "Korean", flag: "🇰🇷" },
  { country: "Thailand", cuisine: "Thai", flag: "🇹🇭" },
  { country: "Vietnam", cuisine: "Vietnamese", flag: "🇻🇳" },
  { country: "Indonesia", cuisine: "Indonesian", flag: "🇮🇩" },
  { country: "Philippines", cuisine: "Filipino", flag: "🇵🇭" },
];
