import type { SeedFood } from "./seed-foods";

export const seedFoodsIndian: SeedFood[] = [
  {
    name: "Ragi (Finger Millet)", slug: "ragi", category: "Millets", emoji: "🌾",
    description: "South India's calcium-and-iron champion grain. Ragi porridge is a beloved first food across Karnataka and Tamil Nadu.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Calcium, iron, fiber, essential amino acids",
    benefits: "One of the best plant calcium sources on earth, plus iron and fiber. Naturally gluten-free. Sprouted ragi flour is even more nutritious.",
    howToChoose: "Fresh ragi flour (check date — millet flour goes rancid faster than wheat). Sprouted ragi malt powder is the premium choice.",
    serve69: "Cook 2 tbsp flour whisked into cold water, stirring continuously 5–7 min until glossy porridge. Thin with breastmilk, formula, or coconut milk. Sweeten only with mashed fruit.",
    serve912: "Thicker porridge with fruit chunks, soft ragi dosa torn into pieces, ragi-banana pancakes.",
    serve12Plus: "Ragi dosa, soft ragi balls (mudde) with sambar, ragi malt in a cup, ragi cookies (low sugar).",
    storage: "Flour keeps 2–3 months airtight (refrigerate in humid climates). Cooked porridge refrigerates 2 days.",
    isIronRich: true, isProteinRich: false,
  },
  {
    name: "Toor Dal (Pigeon Peas)", slug: "toor-dal", category: "Beans & Legumes", emoji: "🫘",
    description: "The everyday dal of South India — creamy when cooked, the backbone of sambar, rasam, and dal-rice.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Protein, iron, folate, B vitamins, fiber",
    benefits: "Excellent affordable protein and iron. Cooks creamy without blending. Pairs with rice for complete protein and with tomato/vitamin C for triple iron absorption.",
    howToChoose: "Oily or unpolished toor dal; uniform yellow color without dust. Unpolished has more fiber.",
    serve69: "Pressure cook until very soft, mash completely smooth with ghee. Thin with warm water. Mix into rice kanji.",
    serve912: "Mashed dal-rice, mild sambar-rice, dal mixed into khichdi and kootu.",
    serve12Plus: "Family sambar, rasam, dal tadka (mild), bisibelebath. Let toddler pour dal over rice.",
    storage: "Dry dal keeps 6–12 months airtight. Cooked dal refrigerates 3–4 days; freezes well in portions.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Moong Dal (Split Mung Beans)", slug: "moong-dal", category: "Beans & Legumes", emoji: "🫘",
    description: "The gentlest lentil for babies — easiest to digest, least gassy, and cooks fastest. The ideal first dal.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Protein, iron, folate, fiber, potassium",
    benefits: "Dissolves into silky soup with minimal cooking. The best starter legume before toor dal, chickpeas, or kidney beans.",
    howToChoose: "Split yellow moong dal (moong dal chilka or dhuli). Whole green moong is for older babies (9m+) as pesarattu.",
    serve69: "Cook until dissolved into soup; strain for the silkiest texture. Stir in ghee and a pinch of cumin and turmeric.",
    serve912: "Dal-rice, khichdi, kootu, pongal. Whole green moong as soft pesarattu from 9 months.",
    serve12Plus: "Sprouted moong (lightly steamed), moong dosa, dal tadka, chaat-style toppings (mild).",
    storage: "Dry dal keeps 6–12 months. Cooked refrigerates 3–4 days; freezes well. Soaked whole moong sprouts in 24–36 hours.",
    isIronRich: true, isProteinRich: true,
  },
  {
    name: "Paneer", slug: "paneer", category: "Dairy & Eggs", emoji: "🧀",
    description: "Fresh Indian cheese — soft, mild, and calcium-packed. Use the softest fresh (malai) paneer for babies.",
    introAgeText: "8 months", introAgeMonths: 8, isAllergen: true, allergenName: "Dairy", containsAllergens: "Cow's milk",
    chokingRisk: "Low",
    nutrition: "Calcium, protein, vitamin A, B12",
    benefits: "Concentrated calcium and protein in a mild flavor babies accept easily. Fresh paneer is lower in sodium than aged cheeses.",
    howToChoose: "Fresh, soft malai paneer — it should yield to pressure. Avoid firm rubbery blocks for babies. Check manufacturing date.",
    serve69: "Wait until 8 months. Then crumble and warm with milk into a soft mash with turmeric and cumin.",
    serve912: "Soft crumbles in rice, mashed into khichdi, mild palak paneer gravy, paneer bhurji (soft scramble style).",
    serve12Plus: "Small soft cubes in curries, tandoori-style baked bites (soft inside), sandwiches, wraps, salads.",
    storage: "Refrigerate submerged in clean water (change daily), use within 2–3 days. Freezes 2 months (texture firms — best for curries).",
    isIronRich: false, isProteinRich: true,
  },
  {
    name: "Ghee", slug: "ghee", category: "Flavor & Fats", emoji: "🫙",
    description: "Clarified butter — the soul of Indian baby food. A spoon of ghee makes dal, rice, and roti both tastier and more nutritious.",
    introAgeText: "6 months", introAgeMonths: 6, isAllergen: true, allergenName: "Dairy", containsAllergens: "Cow's milk (trace casein)",
    chokingRisk: "Low",
    nutrition: "Vitamin A, healthy fats, butyrate",
    benefits: "Butyrate supports gut health; fats help babies absorb vitamins A, D, E, K from vegetables and dal. Makes everything delicious — a genuine nutrition strategy.",
    howToChoose: "A2 or regular cow ghee with a nutty aroma. Granular texture is a good sign. Homemade from butter is excellent.",
    serve69: "Stir 1–2 tsp into dal, rice, khichdi, or porridge per meal. Use for gentle tadkas (cumin in ghee).",
    serve912: "Tadka for dals and vegetables, spread on soft dosa and roti, roasted makhana in ghee.",
    serve12Plus: "Normal family cooking: tadkas, rice, rotis, halwa (occasional), ghee-roasted nuts (4+ only for whole nuts).",
    storage: "Pantry 3+ months airtight (ghee is shelf-stable); refrigerate in very hot climates. Always use a dry spoon.",
    isIronRich: false, isProteinRich: false,
  },
  {
    name: "Jaggery", slug: "jaggery", category: "Flavor & Fats", emoji: "🟤",
    description: "Unrefined cane sugar used in Indian sweets. It is still ADDED SUGAR — wait until 12 months and keep portions small.",
    introAgeText: "12 months+", introAgeMonths: 12, isAllergen: false, allergenName: "", containsAllergens: "",
    chokingRisk: "Low",
    nutrition: "Sugars, trace iron and minerals",
    benefits: "Contains trace minerals unlike white sugar — but the amounts are tiny. Its real value is cultural: festivals and family recipes. Never a health food.",
    howToChoose: "Dark, soft jaggery without white patches. Strain melted jaggery always — it can contain cane fibers and sediment.",
    serve69: "Do not serve — babies under 12 months need no added sugar of any kind. Sweeten with fruit instead.",
    serve912: "Do not serve — keep waiting until the first birthday even though baby eats everything else.",
    serve12Plus: "Small amounts in festive foods (pongal, payasam, ladoo). Keep sweets occasional; fruit remains the everyday sweet.",
    storage: "Airtight container 6+ months. Powdered jaggery dissolves fastest for cooking.",
    isIronRich: false, isProteinRich: false,
  },
];
